.TH "mkindex" "1" "8 March 2022" "TeX Live"
.PP 
.SH "NAME" 
mkindex \- script to process LaTeX index and glossary files
.PP 
.SH "SYNOPSIS" 
.PP 
\fBmkindex\fP \fIBASENAME\fP[\&.idx] \&.\&.\&.
.PP 
.SH "DESCRIPTION" 
.PP 
\fBmkindex\fP runs \fBmakeindex\fP(1) on any index
(\f(CW\&.idx\fP) or glossary (\f(CW\&.glo\fP) files created by TeXing the file
\fI\fIBASENAME\fP\&.tex\fP\&.
.PP 
.SH "FILES" 
.IP "\fIgind\&.ist\fP" 
MakeIndex index style file
.IP 
.IP "\fIgglo\&.ist\fP" 
MakeIndex glossary style file
.IP 
.PP 
.SH "SEE ALSO" 
.PP 
\fBmakeindex\fP(1)
.PP 
.SH "BUGS" 
.PP 
Email bug reports to <https://lists.tug.org/tex-k> (public mailing list).
.PP 
.SH "AUTHOR" 
.PP 
Written by Thomas Esser.
.PP 
This manual page was written by C\&.M\&. Connelly for the Debian
GNU/Linux system\&. It is now maintained as part of TeX Live.
