#!/usr/bin/env perl
# Public domain.  Originally written by Andreas Scherer, 2026.

use strict;
use warnings;

use File::Basename;
use Getopt::Long qw(:config no_ignore_case bundling);
use Pod::Usage;

my $progname;
my $collator;

BEGIN {
  $progname = basename $0;
  # Unicode::Collate has been around a long time,
  # but it's not part of core Perl.
  eval {
    require Unicode::Collate;
    $collator = Unicode::Collate->new();
  };
}

my $usage = "Usage: $progname < input_file > output_file\n";

# Standard options for TeX Live.
Getopt::Long::GetOptions(
  'help|?'  => \&help_handler,
  'version' => sub { print version(); exit 0; }
) or die $usage;
## help_handler()
sub help_handler {
  open(my $pipe, '|-', $ENV{PAGER} || 'less -e') or exit 1;
  pod2usage(-message => version(), -output => $pipe,
    -verbose => 99, -sections => "SHORT DESCRIPTION|EXAMPLE|COPYRIGHT");
  close $pipe;
  exit 0;
}
## version()
sub version {
  return "This is $progname (2026).\n";
}

# Read input from the console and look for blocks like
# \donewithpage\d+
# \[LOCATION KEY TEXPART
# \]EXTERN KEY TEXPART
# and sort them alphabetically by the KEYs.
#
# Every KEY contains a single C identifier (variable, type, function, etc.),
# either as a single brace-enclosed argument of a TeX control sequence,
# or as a single identifier in $math_mode$; the latter come from '@f'ormat
# definitions. All internal backslashes are removed from the KEY before it
# is used in the storage.
my %mini_index; # storage for index entries of a section
my $lines_processed = 0;

foreach my $line (<STDIN>)
{
	if ($line =~ m/\\donewithpage\d+/) { # end of mini-index
		foreach my $key ($collator ?  # (I) sort by second column
			$collator->sort(keys %mini_index) :
			sort {"\L$a" cmp "\L$b"} keys %mini_index) {
			print sort { # (II) sort by third and first column
				my ($a_loc,undef,$a_id) = split / /, $a, 3;
				my ($b_loc,undef,$b_id) = split / /, $b, 3;
				$a_id cmp $b_id || $a_loc cmp $b_loc }
			@{ $mini_index{$key} };
		}
	    print $line;
		%mini_index = (); # reset mini-index storage
	} else { # mini-index entry
		$line =~ s/\\hbox \{\}\\6\\4\\4\{\}//g; # Fix bug in CTWILL
		my (undef,$key) = split / /, $line; # 2nd column is the key
		$key =~ s/\\//g; # strip internal TeX escape(s)
		$key =~ m/\w*\{(\w+)\}/; # extract plain key from control seq.
		$key =~ m/\$(\w+)/ unless defined $1; # extract @f TeX key
		push @{ $mini_index{$1} }, $line; # store index entry
		next; # print later
	}

	$lines_processed++;
}

die $usage unless $lines_processed;

exit 0;

=pod

=encoding utf8

=head1 NAME

ctwill-refsort2 - Sort multiple entries in mini-indexes

=head1 SHORT DESCRIPTION

This small Perl script 'ctwill-refsort2' should be applied after 'refsort' if
you have multiple variants of an identifier in a single section.
formatting with the 'proofmac.tex' macros.
It reads its input from <STDIN> and writes its output to <STDOUT>.

=over

=item Run CTWILL twice on your 'input_file'.w, creating 'input_file'.tex

=item Run TeX on 'input_file'.tex for the first time

=item Invoke "refsort <'input_file'.ref | ctwill-refsort2 >'input_file'.sref"

=item Run TeX on 'input_file'.tex for the second time

=back

See also "man ctwill" for more information on how to use the CTWILL system.

=head1 EXAMPLE

Example from MMIX (https://github.com/ascherer/mmix, 'local' branch):

=over

=item $ tie -c mmixal-twill.ch mmixal.{w,ch,tch}

=item $ ctwill mmixal mmixal-twill (run this two times)

=item $ tex mmixal

=item $ refsort < mmixal.ref | ctwill-refsort2 >mmixal.sref

=item $ tex mmixal

=back

=head1 COPYRIGHT

Public domain.  Originally written by Andreas Scherer, 2026.

Contemporary development on https://github.com/ascherer/cwebbin.

=cut
