.ds V 2.108
.de M
.BR "\\$1" "(\\$2)\\$3"
..
.de Sp
.if n .sp
.if t .sp 0.4
..
.TH CFFTOT1 1 "LCDF Typetools" "Version \*V"
.SH NAME
cfftot1 \- convert PostScript font from CFF to Type 1
.SH SYNOPSIS
.B cfftot1
\%[\fB\-a\fR]
\%[\fIinput\fR [\fIoutput\fR]]
.SH DESCRIPTION
.BR Cfftot1
converts PostScript font programs in the Compact Font Format (CFF) into
Type 1 font programs in PFB or PFA format, preserving all hints that can be
represented in Type 1. The input file should be a raw CFF file or a
PostScript-flavored OpenType font. If the file
.I output
is not specified output goes to the standard output.
If the file
.I input
is not specified input comes from the standard input.
'
.SH OPTIONS
.PD 0
.TP 5
.BI \-a "\fR, " \-\-pfa
Output font in ASCII PFA format.
'
.Sp
.TP 5
.BI \-b "\fR, " \-\-pfb
Output font in binary PFB format. This is the default.
'
.Sp
.TP 5
.BI \-n " name\fR, " \-\-name " name"
Output the CFF's component font named
.IR name .
CFF files can contain more than one font, although few do. Use this option
to select a particular font from a multi-font collection. By default
cfftot1 chooses the collection's first font.
'
.Sp
.TP 5
.BI \-o " file\fR, " \-\-output " file"
Write output font to
.IR file
instead of the standard output.
'
.Sp
.TP 5
.BR \-q ", " \-\-quiet
Do not generate any error messages.
'
.Sp
.TP 5
.BR \-h ", " \-\-help
Print usage information and exit.
'
.Sp
.TP 5
.BR \-v ", " \-\-version
Print the version number and some short non-warranty information and exit.
.PD
'
.SH "SEE ALSO"
.LP
.M t1binary 1 ,
.M t1ascii 1
.LP
.I "Adobe Type 1 Font Format"
.LP
Adobe Technical Notes #5176,
.IR "The Compact Font Format Specification" ,
and #5177,
.I "The Type 2 Charstring Format"
.LP
.IR "OpenType Specification" ,
Version 1.4
'
.SH AUTHOR
Eddie Kohler (ekohler@gmail.com)
