.ds V 1.42
.de M
.BR "\\$1" "(\\$2)\\$3"
..
.TH T1ASCII 1 "" "Version \*V"
.SH NAME
t1ascii \- convert PostScript Type 1 font from binary to ASCII
.SH SYNOPSIS
.B t1ascii
\%[\fB\-l\fR \fIlength\fR]
\%[\fIinput\fR [\fIoutput\fR]]
.SH DESCRIPTION
.BR t1ascii
converts Adobe Type 1 font programs in PFB (binary) format to PFA
(hexadecimal) format. If the file
.I output
is not specified output goes to the standard output.
If the file
.I input
is not specified input comes from the standard input.
'
.SH OPTIONS
.TP 5
.BI \-\-line\-length= "num\fR, " \-l " num"
Set the maximum length of encrypted lines in the output to
.I num.
(These are the lines consisting wholly of hexadecimal digits.) The default
is 64.
'
.TP 5
.BR \-\-warnings ", " \-w
Warn when the input font contains lines longer than 255 characters.
Long lines don't strictly conform to Adobe's Document Structuring
Conventions, and may cause problems with older software.
'
.SH "SEE ALSO"
.LP
.M t1binary 1 ,
.M t1unmac 1 ,
.M t1mac 1 ,
.M t1asm 1 ,
.M t1disasm 1
.LP
.I "Adobe Type 1 Font Format"
.SH AUTHORS
Lee Hetherington (ilh@lcs.mit.edu)
.br
Eddie Kohler (ekohler@gmail.com)
.PP
Ported to Microsoft C/C++ Compiler and MS-DOS operating system by
Kai-Uwe Herbing (herbing@netmbx.netmbx.de).
