.ds V 1.41
.de M
.BR "\\$1" "(\\$2)\\$3"
..
.TH T1BINARY 1  "" "Version \*V"
.SH NAME
t1binary \- convert PostScript Type 1 font from ASCII to binary
.SH SYNOPSIS
.B t1binary
\%[\fB\-l\fR \fIlength\fR]
\%[\fIinput\fR [\fIoutput\fR]]
.SH DESCRIPTION
.B t1binary
converts Adobe Type 1 font programs in PFA (hexadecimal) format to PFB
(binary) format. If the file
.I output
is not specified output goes to the standard output.
If the file
.I input
is not specified input comes from the standard input.
.SH OPTIONS
.TP 5
.BI \-\-block\-length= "length\fR, " \-l " length"
Set the maximum length of sections in PFB output to
.I length.
The default length is as large as memory allows.
.SH "SEE ALSO"
.LP
.M t1ascii 1 ,
.M t1unmac 1 ,
.M t1mac 1 ,
.M t1disasm 1 ,
.M t1asm 1
.LP
.I "Adobe Type 1 Font Format"
.SH AUTHORS
Lee Hetherington (ilh@lcs.mit.edu)
.br
Eddie Kohler (ekohler@gmail.com)
.PP
Ported to Microsoft C/C++ Compiler and MS-DOS operating system by
Kai-Uwe Herbing (herbing@netmbx.netmbx.de).
