.ds V 1.42
.de M
.BR "\\$1" "(\\$2)\\$3"
..
.TH T1MAC 1 "" "Version \*V"
.SH NAME
t1mac \- translate a PFA or PFB PostScript Type 1 font into Macintosh format
.SH SYNOPSIS
.B t1mac
\%[\fB\-\-macbinary\fR | \fB\-\-applesingle\fR |
\fB\-\-appledouble\fR | \fB\-\-binhex\fR | \fB\-\-raw\fR]
\%[\fB\-\-filename\fR \fIname\fR]
\%[\fIinput\fR [\fIoutput\fR]]
.SH DESCRIPTION
.B t1mac
reads a PFA (hexadecimal) or PFB (binary) PostScript Type 1 font file and
generates an equivalent Macintosh Type 1 font file. The output file can be
in MacBinary II, AppleSingle, AppleDouble, or BinHex format, or it can be a
raw resource fork. The default is MacBinary II; use an option to choose a
different format. If the
.I output
file is not specified output goes to the standard output.
.PP
WARNING: The output of
.B t1mac
is not sufficient to use the font, since Macintoshes can't read raw Type 1
fonts. You will need to create a font suitcase containing bitmap fonts if
you do not have such a suitcase for the font already.
.B t1mac
cannot help you do this.
.SH OPTIONS
.TP 5
.BR \-\-raw ", " \-r
Indicates that output should be a raw resource fork.
.TP 5
.BR \-\-macbinary
Indicates that output should be in MacBinary I or II format. This is the
default.
.TP 5
.BR \-\-applesingle
Indicates that output should be in AppleSingle format.
.TP 5
.BR \-\-appledouble
Indicates that output should be in AppleDouble format.
.TP 5
.BR \-\-binhex
Indicates that output should be in BinHex 4.0 format.
.TP 5
.BR \-\-filename "=\fIname\fR, " \-n " \fIname\fR"
Sets the Macintosh filename of the output font to \fIname\fR. The default
is to construct the filename from the font's name using established
Macintosh conventions. This option is not useful when output is a raw
resource fork.
.SH "SEE ALSO"
.LP
.M t1unmac 1 ,
.M t1ascii 1 ,
.M t1binary 1 ,
.M t1asm 1 ,
.M t1disasm 1
.SH AUTHORS
Eddie Kohler (ekohler@gmail.com)
