.ds V 1.41
.de M
.BR "\\$1" "(\\$2)\\$3"
..
.TH T1UNMAC 1  "" "Version \*V"
.SH NAME
t1unmac \- translate a Mac PostScript Type 1 font into PFA or PFB format
.SH SYNOPSIS
.B t1unmac
\%[\fB\-a\fR|\fB\-b\fR]
\%[\fB\-r\fR]
\%[\fIinput\fR [\fIoutput\fR]]
.SH DESCRIPTION
.B t1unmac
extracts POST resources from a Macintosh PostScript font file and creates a
PFA (hexadecimal) or PFB (binary) font file. The file
.I input
should be in MacBinary I or II, AppleSingle, AppleDouble, or BinHex format,
or it can be a raw resource fork. If the file is a raw resource fork, you
need to give the `\-\-raw' option; otherwise
.B t1unmac
should automatically figure out what kind of file you have. If the file
.I output
is not specified output goes to the standard output.
.SH OPTIONS
.TP 5
.BR \-\-pfa ", " \-a
Output in PFA (ASCII) format.
.TP 5
.BR \-\-pfb ", " \-b
Output in PFB (binary) format. This is the default.
.TP 5
.BR \-\-raw ", " \-r
Indicates that the input is a raw resource fork.
.TP 5
.BR \-\-macbinary
Indicates that the input is in MacBinary I or II format.
.TP 5
.BR \-\-applesingle
Indicates that the input is in AppleSingle format.
.TP 5
.BR \-\-appledouble
Indicates that the input is in AppleDouble format.
.TP 5
.BR \-\-binhex
Indicates that the input is in BinHex 4.0 format.
.TP
.BI \-\-block\-length= "num\fR, " \-l " num"
PFB only: Set the maximum output block length to
.I num.
The default length is as large as memory allows.
.TP
.BI \-\-line\-length= "num\fR, " \-l " num"
PFA only: Set the maximum length of encrypted lines in the output to
.I num.
(These are the lines consisting wholly of hexadecimal digits.) The default
is 64.
.SH EXAMPLES
.LP
On Mac OS X, you can use
.B t1unmac
to translate a font into PFA or PFB format as follows:
.nf
% \fBt1unmac\fR \-\-raw FONTFILENAME/..namedfork/rsrc > OUTPUT
.fi
.SH "SEE ALSO"
.LP
.M t1mac 1 ,
.M t1ascii 1 ,
.M t1binary 1 ,
.M t1asm 1 ,
.M t1disasm 1
.SH AUTHORS
Lee Hetherington (ilh@lcs.mit.edu)
.br
Eddie Kohler (ekohler@gmail.com)
.PP
Ported to Microsoft C/C++ Compiler and MS-DOS operating system by
Kai-Uwe Herbing (herbing@netmbx.netmbx.de).
