.ds V 2.108
.de M
.BR "\\$1" "(\\$2)\\$3"
..
.de Sp
.if n .sp
.if t .sp 0.4
..
.TH T1REENCODE 1 "LCDF Typetools" "Version \*V"
.SH NAME
t1reencode \- re-encode a PostScript Type 1 font
.SH SYNOPSIS
.B t1reencode
\%\-e ENCODING
\%[OPTIONS...]
.I font
.RI [ outputfile ]
.SH DESCRIPTION
.BR T1reencode
changes a PostScript Type\~1 font's embedded encoding.  The re-encoded font
is written to the standard output (but see the
.B \-\-output
option).  If no input font file is supplied, 
.B t1reencode
reads a PFA or PFB font from the standard input.
'
.SH OPTIONS
.PD 0
.TP 5
.BR \-\-encoding "=\fIfile\fR, " \-e " \fIfile"
Read the encoding from
.IR file ,
which must contain an encoding in
.M dvips 1
format.  Alternatively,
.I file
can be one of the following special names, in which case the corresponding
standard encoding is used.
.Sp
.RS
.TP 23
.B Name
.B Source
.TP
StandardEncoding
Adobe
.TP
ISOLatin1Encoding
Adobe/ISO (synonym: ISO_8859_1_Encoding)
.TP
ExpertEncoding
Adobe
.TP
ExpertSubsetEncoding
Adobe
.TP
SymbolEncoding
Adobe
.TP
ISOLatin2Encoding
ISO (synonym: ISO_8859_2_Encoding)
.TP
ISOLatin3Encoding
ISO (synonym: ISO_8859_3_Encoding)
.TP
ISOLatin4Encoding
ISO (synonym: ISO_8859_4_Encoding)
.TP
ISOCyrillicEncoding
ISO (synonym: ISO_8859_5_Encoding)
.TP
ISOGreekEncoding
ISO (synonym: ISO_8859_7_Encoding)
.TP
ISOLatin5Encoding
ISO (synonym: ISO_8859_9_Encoding)
.TP
ISOLatin6Encoding
ISO (synonym: ISO_8859_10_Encoding)
.TP
ISOThaiEncoding
ISO (synonym: ISO_8859_11_Encoding)
.TP
ISOLatin7Encoding
ISO (synonym: ISO_8859_13_Encoding)
.TP
ISOLatin8Encoding
ISO (synonym: ISO_8859_14_Encoding)
.TP
ISOLatin9Encoding
ISO (synonym: ISO_8859_15_Encoding)
.TP
KOI8REncoding
-
.RE
'
.Sp
.TP 5
.BR \-\-encoding\-text "=\fItext\fR, " \-E " \fItext"
Use the encoding in the
.I text
argument, which must be formatted as a
.M dvips 1
encoding.  One of
.B \-\-encoding
and
.B \-\-encoding\-text
must be supplied.
'
.Sp
.TP 5
.BR \-\-name "=\fIname\fR, " \-n " \fIname"
Set the output font's PostScript name to
.IR name .
The default is the input font name followed by the encoding's name.
'
.Sp
.TP 5
.BR \-\-full-name "=\fIname\fR, " \-N " \fIname"
Set the output font's FullName to
.IR name .
The default is the input FullName followed by the encoding's name.
'
.Sp
.TP 5
.BR \-\-output "=\fIfile\fR, " \-o " \fIfile"
Send output to
.I file
instead of standard output.
'
.Sp
.TP 5
.BR \-\-pfb ", " \-b
Output a PFB font.  This is the default.
'
.Sp
.TP 5
.BR \-\-pfa ", " \-a
Output a PFA font.
'
.Sp
.TP 5
.BR \-h ", " \-\-help
Print usage information and exit.
'
.Sp
.TP 5
.BR \-\-version
Print the version number and some short non-warranty information and exit.
.PD
'
.SH "RETURN VALUES"
.B T1reencode
exits with value 0 if a re-encoded font was successfully generated, and 1
otherwise.
'
.SH "NOTES"
.LP
.B T1reencode
should be used only in special situations.  It's generally much better to
use PostScript commands to re-encode a font; for instance, executing the
PostScript commands to generate two differently-encoded versions of a
single font will take up much less memory than loading two
.BR t1reencode d
fonts.
'
.SH "EXAMPLES"
.PP
This command re-encodes Frutiger Roman in the ISO Latin\~1 encoding.  The new
font will have the PostScript name Frutiger-RomanISOLatin1Encoding.
.Sp
.nf
    \fBt1reencode\fR \fB\-e\fR ISOLatin1Encoding FrutiRom.pfb \e
            \fB\-o\fR FrutiRomISOL1.pfb
.fi
.Sp
This series of commands, which use
.M cfftot1 1
and
.M otftotfm 1
as well as
.B t1reencode
itself, generate a version of Warnock Pro Regular with old-style figures in
the slots for numbers (because of
.BR otftotfm 's
.BR \-f onum
option).  The new font will be called WarnockPro-RegularOsF.
.Sp
.nf
    \fBotftotfm\fR \fB\-f\fRonum WarnockPro-Regular.otf \e
            \fB\-\-output\-encoding\fR /tmp/osf.enc
    \fBcfftot1\fR WarnockPro-Regular.otf | \fBt1reencode\fR \fB\-e\fR /tmp/osf.enc \e
            \fB\-n\fR WarnockPro-RegularOsF \fB\-N\fR "Warnock Pro Regular OsF" \e
            \fB\-o\fR WarnoProRegOsF.pfb
.fi
'
.SH "SEE ALSO"
.LP
.IR "Adobe Type 1 Font Format" ,
.M dvips 1 ,
.M cfftot1 1 ,
.M otftotfm 1
'
.SH AUTHOR
Eddie Kohler (ekohler@gmail.com)
