.\" -*-nroff-*-
.ds V 2.108
.de M
.BR "\\$1" "(\\$2)\\$3"
..
.ds E " \-\- 
.if t .ds E \(em
.de Op
.BR "\\$1" "\\$2" "\\$3" "\\$4" "\\$5" "\\$6"
..
.de Oy
.BI "\\$1\fR=" "\\$2\fR, " "\\$3\& " "\\$4" "\\$5" "\\$6"
..
.de Ol
.BI "\\$1\fR=" "\\$2" "\\$3" "\\$4" "\\$5" "\\$6"
..
.de Sp
.if n .sp
.if t .sp 0.4
..
.de Es
.Sp
.RS 5
.nf
..
.de Ee
.fi
.RE
.PP
..
.TH MMAFM 1 "LCDF Typetools" "Version \*V"
.SH NAME
mmafm \- creates AFM font metrics for multiple master fonts
'
.SH SYNOPSIS
.B mmafm
\%[OPTIONS...]
.I font
'
.SH DESCRIPTION
.B Mmafm
creates AFM font metrics for PostScript multiple master fonts by
interpolation. You pass it an AMFM file (multiple master font metrics) and
options specifying the design point you want, and it writes the resulting
AFM file to the standard output.
.PP
Each
.I font
argument is either the filename of an AFM or AMFM font metrics file, or a
PostScript font name. If you give a font name,
.B mmafm
will look up the actual font metrics file using the PSRESOURCEPATH
environment variable. This colon-separated path is searched for `PSres.upr'
files, an Adobe method for indexing PostScript resources.
.PP
You can also give the name of a multiple master font instance, like
`MinionMM_367_400_12_'.
.B Mmafm
will parse the font name and create that instance for you. `PSres.upr'
files must be set up for this to work.
.PP
Any multiple master font should be distributed with a single AMFM file and
several AFM files (one for each master). For Myriad, for example, the AMFM
file is MyriadMM.amfm and the AFM files are MyriadMM-LightCn.afm,
MyriadMM-LightSemiEx.afm, MyriadMM-BlackCn.afm, and
MyriadMM-BlackSemiEx.afm.
.B Mmafm
needs to find all these files to function. For fonts in the Adobe type
library, you can download the necessary files from
<http://www.lcdf.org/type>; look for the mm-metrics package.
.PP
You must always supply the AMFM file (or its font name) on the command
line, but
.B mmafm
will look for any required AFM files you don't supply yourself. It tries
the PSRESOURCEPATH environment variable, and also looks for files named
`\fIFontName\fR.afm' or `\fIFontName\fR.AFM' in the directory that
contained the AMFM file. (The Myriad filenames given above fit this
pattern.)
.PP
.B Mmafm
supports fonts with intermediate masters, like Adobe Jenson and Kepler. If
your PSRESOURCEPATH environment variable is set up, it will handle these
fonts automatically. Otherwise, you must first run 
.RB ` "mmpfb \-\-amcp\-info" '
on the font outline files to create auxiliary AMCP files for these fonts.
Each AMCP file should be in the same directory as its corresponding AMFM
file and should have the same root filename, but with a `.amcp' extension
instead of `.amfm'. See
.M mmpfb 1
for more information.
'
'
.SH EXAMPLE
'
.nf
% mmafm \-\-weight=400 \-\-width=600 MyriadMM.amfm > MyriadMM_400_600_.afm
.fi
'
.SH OPTIONS
Long options may be abbreviated to their unique prefixes.
'
.TP 5
.Oy \-\-output file \-o file
Send output to
.I file
instead of standard output.
'
.TP
.Oy \-\-weight N \-w N
Set the weight axis to 
.IR N .
'
.TP
.Oy \-\-width N \-W N
Set the width axis to 
.IR N .
'
.TP
.Oy \-\-optical\-size N \-O N
Set the optical size axis to 
.IR N .
'
.TP
.Ol \-\-style N
Set the style axis to 
.IR N .
.TP
\fB\-\-1\fR=\fIN\fR (\fB\-\-2\fR=\fIN\fR, \fB\-\-3\fR=\fIN\fR, \fB\-\-4\fR=\fIN\fR)
Set the first (second, third, fourth) axis to
.IR N .
'
.TP
.Oy \-\-precision N \-p N
Round output numbers so they have at most
.I N
digits after the decimal point. Smaller numbers are less precise; `\fB\-p
\fR0' rounds all numbers to integers. The default precision is 3.
'
.TP
.Oy \-\-min\-kern N \-k N
Only output kerning pairs whose absolute value is
.IR N
or larger. Smaller minimum kerns make kerning more precise and the output
AFM file bigger. The default minimum kern is 2.0.
'
.SH TROUBLESHOOTING
.PP
Some programs, such as TeX's
.BR fontinst ,
can choke on AFM files that include fractional numbers. Therefore, if you
have trouble with an AFM file, try rerunning
.B mmafm
with the
.Op \-\-precision=0
option.
'
.SH SEE ALSO
.M mmpfb 1
'
.SH DIAGNOSTICS
.TP 5
\fIFont\fR requires intermediate master conversion programs
You haven't yet created an AMCP file for \fIFont\fR.
'
.SH AUTHOR
.na
Eddie Kohler, ekohler@gmail.com
.PP
The latest version is available from:
.br
http://www.lcdf.org/type/
.br
AMFM and AFM files for Adobe Type Library fonts are also available at that
URL.
.PP
Thanks to Melissa O'Neill for suggestions and patient
debugging.
