.TH "fontinst" "1" "8 March 2022" "TeX Live"
.PP 
.SH "NAME" 
fontinst \- utility to run TeX as fontinst 
.PP 
.SH "SYNOPSIS" 
.PP 
\fBfontinst\fP \fIpackage\fP
.PP 
.SH "DESCRIPTION" 
.PP 
\fBfontinst\fP runs \fBtex\fP(1) with the \fB--progname\fP flag set to
pretend to be the program fontinst (affecting Karl Berry paths)\&.
.PP 
Typing
.PP 
\f(CWfontinst fontinst\&.sty\fP
.PP 
will start \fBtex\fP(1) and give the user an interactive prompt
(\f(CW*\fP) where fontinst commands can be typed (such as
\f(CW\elatinfamily{ptm}{}\ebye\fP)\&.
.PP 
.SH "SEE ALSO" 
.PP 
\fBtex\fP(1)
.PP 
The fontinst manual, \fIfontinst\&.tex\fP\&.
.PP 
Web page: <https://tug.org/applications/fontinst/>
.PP 
.SH "BUGS" 
.PP 
Email bug reports to <https://lists.tug.org/fontinst> (public mailing list).
.PP 
.SH "AUTHOR" 
.PP 
Thomas Esser
.PP 
This manual page was written by C\&.M\&. Connelly for the Debian
GNU/Linux system\&. It is now maintained as part of TeX Live.
