rem Build ApTeX on Visual Studio 2015.
echo Building zlib ...
nmake -nologo -f mk-zlib.nmake
echo Building libpng ...
nmake -nologo -f mk-libpng.nmake
echo Building freetype ...
nmake -nologo -f mk-freetype.nmake
echo Building libotf ...
nmake -nologo -f mk-libotf.nmake
echo Building libyaml ...
nmake -nologo -f mk-libyaml.nmake
echo Building libpixman ...
nmake -nologo -f mk-libpixman.nmake
echo Building libcairo ...
nmake -nologo -f mk-libcairo.nmake
