rem Build ApTeX on Visual Studio.
echo Building zlib ...
nmake -nologo -f mk-zlib.nmake
echo Building libpng ...
nmake -nologo -f mk-libpng.nmake
echo Building freetype ...
nmake -nologo -f mk-freetype.nmake
echo Building libotf ...
nmake -nologo -f mk-libotf.nmake
