.TH DISDVI 1 "25 March 2019"
.SH NAME
disdvi \- `disassemble' a (p)TeX or XeTeX DVI file
.SH SYNOPSIS
.B disdvi
.RB [ \-p ]
.RI [ dvi_file [ \fB.dvi\fP ]]
.br
.B disdvi \-x
.RI [ xdv_file [ \fB.xdv\fP ]]
.br
.B disdvi \-h
.SH DESCRIPTION
.I disdvi
interprets the contents of
.I dvi_file
or
.I xdv_file
printing the DVI commands and text in a human-readable ASCII format on
the standard output.
.SH "SEE ALSO"
.BR dvi2tty (1)
.SH AUTHOR
Marcel J.E.\& Mol, Delft University of Technology, The Netherlands
.br
marcel@mesa.nl, MESA Consulting
