.\" This manpage is licensed under the GNU Public License
.TH TEX2ASPC 1 2018-02-14  "" ""

.SH NAME

tex2aspc \- converts conventional MusiXTeX scores to .aspc format 
for processing by
.BR autosp (1).

.SH SYNOPSIS

.B tex2aspc 
.RB  [ \-v\ |\ \-\-version\ |\ \-h\ |\ \-\-help ]

.B tex2aspc
.IR infile [\fR.tex\fP]
.RI [ outfile [ \fR.aspc\fP ]]

.SH DESCRIPTION

This program re-factors (sequences of) conventional 
note-spacing commands (\\notes \\Notes \\NOtes ...)
in a measure 
into
a single \\anotes command.
This is intended for "legacy" scores in order to take advantage of
features 
only provided by 
.BR autosp (1),
such as "global" skips and processing of \TransformNotes commands.

.SH LIMITATIONS


.B tex2aspc
assumes that & and | (rather than \\nextinstrument and \\nextstaff) are used to separate instruments and staffs.

User-defined macros are not processed or expanded.

.SH SEE ALSO
.BR autosp (1)
.PP 
musixdoc.pdf

.SH AUTHOR 
This program and manual page were written by Bob Tennent <rdt@cs.queensu.ca>.


