.TH scor2prt 1 "2 Feb 2016" "Version 2.7.3" "scor2prt Manual Page"
.SH NAME
scor2prt \- source-parts separation program for pmx, a MusiXTeX preprocessor
.SH SYNOPSIS
.B scor2prt
.RI basename [.pmx]
.SH DESCRIPTION
scor2prt is part of pmx(1), a preprocessor for MusiXTeX. It can automatically
create parts from a score by generating a set of .pmx files, one for each part,
from a single .pmx file for the score. The appearance of the parts can be
controlled by special commands in the main file. Read the PMX Manual for more
information about that.
.SH SEE ALSO
pmx(1), pmxab(1), musixtex(1), PMX Manual
.SH AUTHORS
PMX was written by Don Simons <dsimons@roadrunner.com>.
This manual page was written by Roland Stigge <stigge@antcom.de> for the Debian
project and revised by Bob Tennent <rdt@cs.queensu.ca>.
