.\" man page for cef5conv
.\" Copyright (C) 1994-2015  Werner Lemberg <wl@gnu.org>
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program in doc/COPYING; if not, write to the Free
.\" Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
.\" MA 02110-1301 USA
.
.TH CEF5CONV 1 18-Apr-2015 "CJK Version 4.8.4"
.
.\" ====
.\" ==== macro definitions
.\" ====
.
.\" here we define \TeX for troff and nroff
.if t .ds TX \fRT\\h'-0.1667m'\\v'0.20v'E\\v'-0.20v'\\h'-0.125m'X\fP
.if n .ds TX TeX
.
.\" and here the same for \LaTeX
.if t \{\
.ie '\*(.T'dvi' \
.ds LX \fRL\h'-0.36m'\v'-0.15v'\s-3A\s0\h'-0.15m'\v'0.15v'\fP\*(TX
.el .ds LX \fRL\h'-0.36m'\v'-0.22v'\s-2A\s0\h'-0.15m'\v'0.22v'\fP\*(TX
.\}
.if n .ds LX LaTeX
.
.\" \LaTeXe
.\" note that we need \vareps for TeX instead of \eps which can only be
.\" accessed with the \N escape sequence (in the Math Italic font)
.if t \{\
.ie '\*(.T'dvi' .ds LE \*(LX\h'0.15m'2\v'0.20v'\f(MI\N'34'\fP\v'-0.20v'
.el .ds LE \*(LX\h'0.15m'2\v'0.20v'\(*e\v'-0.20v'
.\}
.if n .ds LE LaTeX\ 2e
.
.\" a typewriter font
.if t \{\
.de C
\fC\\$1\fP
..
.\}
.if n \{\
.de C
\\$1
..
.\}
.
.\" ====
.\" ==== end of macro definitions
.\" ====
.
.
.
.SH NAME
cef5conv \- convert a TeX document in Big\ 5 encoding containing CEF macros
into `preprocessed' form.
.
.
.SH SYNOPSIS
.B cef5conv
<
.I infile
>
.I outfile
.
.
.SH DESCRIPTION
The
.B Chinese Encoding Framework
.RB ( CEF )
developed by Christian Wittern
.C <cwittern@conline.central.de>
makes it possible to include CJK characters in various encodings using the
SGML macros
.B &CX-aabb;
for Big\ 5 and CNS encoding and
.B &U-aabb;
for Unicode
.RB ( X
denotes a number between 0 and 7; 0 represents Big\ 5 encoding, 1-7 CNS
encoding planes 1-7.
.B aabb
is either a decimal or hexadecimal number).
.PP
.B cef5conv
converts the CEF macros of a Big\ 5 encoded document together with the Big\
5 encoding itself into a form which can directly processed with \*(LE.
It is identical to
.IP
.B bg5conv
<
.I infile
|
.B cefconv
>
.I outfile
.PP
This filter is part of the
.B CJK
macro package for \*(LE.
.
.
.SH "SEE ALSO"
.BR \%sjisconv (1),
.BR bg5conv (1),
.BR \%cefconv (1),
.BR \%cefsconv (1),
.BR \%extconv (1),
.br
the
.B CJK
documentation files.
.
.
.SH AUTHOR
Werner Lemberg
.C <wl@gnu.org>
