.TH "mkocp" "1" "8 March 2022" "TeX Live"
.PP 
.SH "NAME" 
mkocp \- frontend to \fBotp2ocp\fP(1)
.SH "SYNOPSIS" 
.B mkocp
.I OTPFILE
.SH "DESCRIPTION" 
.PP 
\fBmkocp\fP is used to create or recreate Omega Compiled Process files
(binary) from Omega Translation Process (text) files\&.
.PP 
Omega Translation Processes are used to translate one character set to
another and to choose between characters with one or more
context-sensitive variants\&.  OTPs could also be used to change the
case or hyphenation of text\&.
.PP 
OTPs are defined in text files, and compiled into binary code (OCPs)
using \fBmkocp\fP (this script) or directly with \fBotp2ocp\fP(1)\&.
.PP 
.SH "FILES" 
.IP "\fIOTPFILE\fP" 
An Omega Typesetting Process filter file\&.
.PP 
.SH "SEE ALSO" 
.PP 
\fBomega\fP(1), \fBotp2ocp\fP(1)\&.
.PP
<https://ctan.org/pkg/omega>
.PP 
.SH "BUGS" 
.PP 
Email bug reports to <https://lists.tug.org/tex-k> (public mailing list).
.PP 
.SH "AUTHOR" 
.PP 
\fBmkocp\fP is part of Omega\&.  The primary authors of Omega are John Plaice
and Yannis Haralambous\&.
.PP 
This manual page was written by C\&.M\&. Connelly for the Debian
GNU/Linux system\&. It is now maintained as part of TeX Live.
