.TH "mkofm" "1" "8 March 2022" "TeX Live"
.PP 
.SH "NAME" 
mkofm \- front end to \fBmktextfm\fP(1)
.SH "SYNOPSIS" 
.B mkofm
.I ARGS
.SH "DESCRIPTION" 
.PP 
\fBmkofm\fP takes all \fIARGS\fP and passes them to
\fBmktextfm\fP(1)\&.  For more information about appropriate
arguments, see \fBmktextfm\fP(1)\&.
.PP 
.SH "SEE ALSO" 
.PP 
\fBmktextfm\fP(1)
<https://ctan.org/pkg/omega>
.PP 
.SH "BUGS" 
.PP 
Email bug reports to <https://lists.tug.org/tex-k> (public mailing list).
.PP 
.SH "AUTHOR" 
.PP 
\fBmkofm\fP is part of Omega\&.  The primary authors of Omega are John Plaice
and Yannis Haralambous\&.
.PP 
This manual page was written by C\&.M\&. Connelly for the Debian
GNU/Linux system\&. It is now maintained as part of TeX Live.
