.TH "otp2ocp" "1" "8 March 2022" "TeX Live"
.PP 
.SH "NAME" 
otp2ocp \- convert Omega Translation Process files to Omega
Compiled Process files
.SH "SYNOPSIS" 
.B otp2ocp
.IR OTPFILE [ \fB.otp\fP ]
.RI [ OCPFILE [ \fB.ocp\fP ]]
.SH "DESCRIPTION" 
.PP 
\fBotp2ocp\fP is used to create or recreate Omega Compiled Process
files (binary) from Omega Translation Process (text) files\&.
.PP 
Omega Translation Processes are rules used to translate one character
set to another and to choose between characters with one or more
context-sensitive variants\&.  OTPs could also be used to change the
case or hyphenation of text\&.
.PP 
.SH "SEE ALSO" 
.PP 
\fBmkocp\fP(1), \fBomega\fP(1)\&.
.PP
<https://ctan.org/pkg/omega>
.PP 
.SH "AUTHOR" 
.PP 
\fBmkocp\fP is part of Omega\&.  The primary authors of Omega are John Plaice
and Yannis Haralambous\&.
.PP 
This manual page was written by C\&.M\&. Connelly for the Debian
GNU/Linux system\&. It is now maintained as part of TeX Live.
