.TH MAKEJVF 1
\"=====================================================================
.if t .ds TX \fRT\\h'-0.1667m'\\v'0.20v'E\\v'-0.20v'\\h'-0.125m'X\fP
.if n .ds TX TeX
.\" LX definition must follow TX so LX can use TX
.if t .ds LX \fRL\\h'-0.36m'\\v'-0.15v'\s-2A\s0\\h'-0.15m'\\v'0.15v'\fP\*(TX
.if n .ds LX LaTeX
\"=====================================================================
.SH NAME
makejvf \- Make Japanese VF file from Japanese \*(TX TFM file
.SH SYNOPSIS
\fBmakejvf\fR [<\fIoptions\fR>] <\fI\*(TX TFM file\fR> <\fIPS font TFM\fR>
.SH DESCRIPTION
\fBmakejvf\fR is a tool to generate Japanese VF file from Japanese \*(TX TFM
(JFM) file for use with dvips.
.TP 5
When processing Japanese texts, p\*(TX refers to JFM (min10.tfm, jis.tfm \
etc.), which includes definitions of some different character widths and \
metric glue/kerns. For most punctuations and quotation marks, the \
character widths are truncated to less than 1 zw (zenkaku-width; the \
width of ordinary Kanji characters), and metric glue/kerns are inserted \
as a substitute.
.TP 5
On the other hand, in Japanese PS fonts, all punctuations and quotation \
marks have the same character widths as ordinary Kanji characters. \
For this reason, when dvips processes the resulting DVI, these characters \
have to be shifted to the left by the amount of glue/kerns inserted.
.TP 5
To achieve this, Virtual fonts (VF) and PS TFM files are required; \
When VF contains the commands of shifting characters, PS font TFM can \
have the exact character widths of PS fonts.
.TP 5
The program \fBmakejvf\fR can be used for this purpose. \
It inputs a p\*(TX JFM file (refered to as <\fI\*(TX TFM file\fR> in \
\fBSYNOPSIS\fR above), and outputs a corresponding VF file \
(with the same basename as <\fI\*(TX TFM file\fR>) and \
a JFM file for a PS font JFM file (<\fIPS font TFM\fR> above).
.SH OPTIONS
.PP
.TP 10
\fB-C\fR
Condensed ("Cho-tai") mode.
.TP 10
\fB-K\fR <\fIPS-TFM\fR>
Map Kana (more exactly, non-Kanji) characters to another PS font JFM
named <\fIPS-TFM\fR>.
.TP 10
\fB-b\fR <\fIinteger\fR>
Base line shift amount; the \fIinteger\fR represents a relative value,
using the character height as a base of 1000.
When a positive integer is specified, the characters are lowered.
When a negative integer is specified, the characters are raised.
.TP 10
\fB-m\fR
Replace single/double quotation marks (', '') with single/double prime
quotation marks (so-called "minute") in vertical writing.
The replacement is realized by manipulating glyphs of prime and
double prime (JIS 0x216C and 0x216D; Unicode U+2032 and U+2033),
\fInot\fR by putting actual glyphs designed for quotation marks
(Unicode U+301D and U+301E/U+301F).
.TP 10
\fB-a\fR <\fIAFMfile\fR>
Name of the input AFM file used for Kana-tsume mode.
This option is unsupported.
.TP 10
\fB-k\fR <\fIinteger\fR>
Kana-tsume (narrower spaces between Kana characters) margin amount;
the \fIinteger\fR represents a relative value, using the character width
as a base of 1000. This option should be accompanied with \fB-a\fR option.
This option is unsupported.
.TP 10
\fB-i\fR
Start mapped font ID from No. 0 in output VF
(by default, makejvf defaults to No. 1).
.TP 10
\fB-e\fR
Enhanced mode; the horizontal shift amount is determined from the
glue/kern table of input JFM file.
.TP 10
By default, \fBmakejvf\fR uses the hard-coded value as the horizontal \
shift amount, which is (mostly) optimized for Japanese fonts. \
When enhanced mode (option \fB-e\fR) is enabled, the shift amount is \
determined from the input p\*(TX TFM (JFM) file, which is likely to \
output most suitable VF for the JFM.
.TP 10
For most standard Japanese JFM (like jis.tfm and its derivatives), \
the output VFs from both modes will have no significant difference. \
For simplified/traditional Chinese JFM (like upschrm-h.tfm and \
uptchrm-h.tfm), the output VF from enhanced mode will be better. \
For min10.tfm and its derivatives, enhanced mode should \fInever\fR be \
enabled, since the characterization in min10.tfm is non-standard.
.TP 10
\fB-t\fR <\fICNFfile\fR>
Use <\fICNFfile\fR> as a configuration file.
.TP 10
\fB-u\fR <\fICharset\fR>
UCS mode. Available charsets are: gb (GB = Simplified Chinese),
cns (CNS = Traditional Chinese), ks (KS = Korean),
jis (JIS = Japanese), jisq (JIS quote only),
custom (user-defined CHARSET from <CNFfile>;
see \fBCONFIGURATION FILE FORMAT\fR section).
.TP 10
Options below are effective only in UCS mode:
.TP 10
\fB-J\fR <\fIPS-TFM\fR>
Map single/double quote to another JIS-encoded PSfont TFM.
.TP 10
\fB-U\fR <\fIPS-TFM\fR>
Map single/double quote to another UCS-encoded PSfont TFM.
.TP 10
\fB-3\fR
Use set3, that is, enable non-BMP characters support (with UCS mode).
By default \fBmakejvf\fR does not output >=U+10000, to reduce file
size and to avoid problems with old DVI drivers. Recent versions of
dvipdfmx and others can handle VF with >=U+10000 (= set3 in DVI
language), therefore \fB-3\fR might be helpful.
.TP 10
\fB-H\fR
Use half-width Katakana.
.SH EXAMPLE
.TP 5
If you want to use min10 as Ryumin-Light-H, run
     makejvf min10.tfm rml
.TP 5
This generates min10.vf and rml.tfm. Put these files in an appropriate \
directory under TEXMF tree, and add the following line to psfonts.map.
     rml Ryumin-Light-H
.SH CONFIGURATION FILE FORMAT
.TP 5
With \fB-t\fR option, you can give \fBmakejvf\fR a custom settings \
for generating VF. The syntax is:

     % comment line
     MOVE	<code>	<right>	<down>
     
     REPLACE	<code>	<new code>
     CHARSET	<code>,<code>,<code>..<code>,<code>,
     +	<code>,<code>..<code>

.TP 5
Each line should begin with a command, and should be TAB-separated. \
Line starting with % is a comment, and empty lines are ignored.
.TP 5
The \fBMOVE\fR command specifies horizontal/vertical shift amount \
for the individual character <\fIcode\fR>. \
The \fBREPLACE\fR command replaces the character <\fIcode\fR> with \
<\fInew code\fR>. \
The \fBCHARSET\fR command sets the custom character set of output VF; \
the + character continues from the previous line.
.TP 5
An example usage can be found in uptex-fonts project. \
See GitHub repository
     <https://github.com/texjporg/uptex-fonts>.
.SH SEE ALSO
More detailed description of \fBmakejvf\fR in Japanese is available at
     $TEXMFDIST/doc/fonts/ptex-fonts/README_makejvf
.SH AUTHOR
This manual page was written by Japanese \*(TX Development Community \
<https://texjp.org>. For more information, see GitHub repository \
<https://github.com/texjporg/ptex-fonts>.
.TP 5
Many thanks to Atsuhito KOHDA <kohda@debian.org>, \
for providing another manpage in Debian GNU/Linux system.
