.TH PSRESIZE 1 "PSUtils"
.SH NAME
psresize \- rescales and centers a document for new output paper size
.SH SYNOPSIS
.B psresize
.RB [ \-w\fIwidth\fR ]
.RB [ \-h\fIheight\fR ]
.RB [ \-p\fIpaper\fR ]
.RB [ \-W\fIwidth\fR ]
.RB [ \-H\fIheight\fR ]
.RB [  \-P\fIpaper\fR ]
.RB [ \-q ]
.RI [ infile
.RI [ outfile ]]
.SH DESCRIPTION
.B Psresize
rescales and centres a document on a different size of paper.
The input PostScript file should follow the Adobe Document Structuring
Conventions.
.PP
The
.B \-w
option gives the output paper width, and the
.B \-h
option gives the output paper height, normally specified in
.B "cm"
or
.B "in"
to convert 
PostScript's points (1/72 of an inch)
to centimeters or inches.
The 
.B \-p
option can be used instead, to set the paper size; otherwise a default value is used.
See
.BR paper (1).
.PP
The
.B \-W
option gives the input paper width, and the
.B \-H
option gives the input paper height.
The 
.B \-P
option can be used instead, to set the paper size; otherwise a default value is used.
See
.BR paper (1).
.PP
.B Psresize
normally prints the page numbers of the pages output; the
.B \-q
option suppresses this.
.SH EXAMPLES
The following command can be used to convert a document on A4 size paper to
letter size paper:
.sp
psresize -PA4 -pletter in.ps out.ps
.sp
.SH AUTHOR
Written by Angus J. C. Duggan.
.SH "SEE ALSO"
.Br psutils (1)
.SH TRADEMARKS
.B PostScript
is a trademark of Adobe Systems Incorporated.
.SH BUGS
.B Psresize
does not accept all DSC comments.
