.TH PSSELECT 1 "PSUtils"
.SH NAME
psselect \- select pages from a PostScript file
.SH SYNOPSIS
.B psselect
.RB [ \-q ]
.RB [ \-e | \-o ]
.RB [ \-r ]
.RB [[ \-p ] \fIpages\fR ]
.RI [ infile
.RI [ outfile ]]
.SH DESCRIPTION
.B Psselect
selects pages from a PostScript document, creating a new PostScript file. The
input PostScript file should follow the Adobe Document Structuring
Conventions.
.PP
The 
.B \-e
option selects all of the even pages; it may be used in conjunction with the
other page selection options to select the even pages from a range of pages.
.PP
The 
.B \-o
option selects all of the odd pages; it may be used in conjunction with the
other page selection options.
.PP
The 
.BI \-p pages
option specifies the pages which are to be selected.
.I Pages
is a comma separated list of page ranges, each of which may be a page number,
or a page range of the form
.IB first \- last .
If
.I first
is omitted, the first page is assumed, and if
.I last
is omitted, the last page is assumed.

The prefix character `_' indicates that the page number is relative to the end
of the document, counting backwards. If just this character with no page
number is used, a blank page will be inserted.
.PP
The 
.B \-r
option causes
.B psselect
to output the selected pages in reverse order.
.PP
.B Psselect
normally prints the page numbers of the pages rearranged; the
.B \-q
option suppresses this.
.PP
If any of the
.BR \-r ,
.BR \-e ,
or
.B \-o
options are specified, the page range must be given with the
.B \-p
option. This is for backwards compatibility with previous versions.

.SH NOTES
The page number given to
.I psselect
is the number of the page counting from the start or end of the file, starting
at one. The actual page number in the document may be different.
.SH AUTHOR
Written by Angus J. C. Duggan.
.SH "SEE ALSO"
.BR psutils (1)
.SH TRADEMARKS
.B PostScript
is a trademark of Adobe Systems Incorporated.
.SH BUGS
.I Psselect
does not accept all DSC comments.
