.TH PSUTILS 1 "PSUtils"
.SH NAME
PSUtils \- utilities
.SH DESCRIPTION
PSUtils is a set of utilities for manipulating PostScript
documents which follow the Adobe Document Structuring Conventions.
.SH AUTHOR
Written by Angus J. C. Duggan.
.SH "SEE ALSO"
.BR psbook (1),
.BR psselect (1),
.BR pstops (1),
.BR epsffit (1),
.BR psnup (1),
.BR psresize (1),
.BR psjoin (1),
.BR extractres (1),
.BR includeres (1)
.SH TRADEMARKS
.B PostScript
is a trademark of Adobe Systems Incorporated.
