.TH TPIC2PDFTEX 1 2008-08-01 GNU "Tex Live Manpage"

.\"$Id: tpic2pdftex.1,v 1.15 2010/01/16 12:13:17 hahe Exp hahe $
.\"
.\" Copyright (C) 2002--2008 by Hartmut Henkel
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or (at
.\" your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.\" See the GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the
.\" Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
.\" MA  02111-1307  USA

.SH NAME
tpic2pdftex \- convert tpic \\specials for use by pdftex

.SH SYNOPSIS
.B pic
-t
.I somefile.pic
|
.B tpic2pdftex
>
.I somefile.tex

Process
.IR somefile.tex
by
.BR pdftex/pdflatex.

.SH DESCRIPTION
Experimental
.B awk
script for conversion of
.B tpic
\\specials as produced
by
.B (groff-)pic
into
.B pdfTeX
\\pdfliteral sections for further processing
by
.B pdftex.

.SH NOTES
Current version: 1.97.

.B tpic
\\special
description see e. g.:
Goossens, Rahtz, Mittelbach: The LaTeX Graphics Companion,
Addison-Wesley, 1997, pp. 464.

.SH BUGS
Spline curve shapes not fully authentic (unknown algorithm).
Bounding box does not care for line thickness (groff pic feature).
Splines might be outside bounding box.
Fill color does not work correctly for arrowheads (pic limitation).

.SH SEE ALSO
.BR pic (1),
.BR grap (1),
.BR groff (1),
.BR awk (1),
.BR pdftex (1).
