.\" This manpage is licensed under the GNU Public License
.TH MSXLINT 1 2015-02-05  "" ""

.SH NAME
msxlint \- detects incorrectly formatted notes lines in a MusiXTeX source file.

.SH SYNOPSIS
.B msxlint
.RB [ \-v\ |\ \-\-version\ |\ \-h\ |\ \-\-help ]

.B msxlint
.RB [ \-d\  | \ \-\-debug ]...
.RI [ infile [ \fB.tex\fP ]...]

If no
.IR infiles
are specifed, standard input is used.

.SH USAGE

The format that notes commands are expected to match is
determined by \\instrumentnumber and \\setstaffs commands, or
uses of the \\TransformNotes macro defined in musixtnt.tex (see musixdoc.pdf), or re-definitions of the \\vnotes macro.  
Output consists of messages about format errors,
with listings of the ill-formatted lines. 

.SH LIMITATIONS
User-defined  macros are not processed or expanded.  Notes commands (\\notes, \\Notes, etc.)
can have line breaks, but other commands must fit on one line.
.SH SEE ALSO
.BR fixmsxpart (1)
.PP
musixdoc.pdf

.SH AUTHOR 
This program and manual page were written by Bob Tennent <rdt@cs.queensu.ca>.
