.ds V 2.108
.de M
.BR "\\$1" "(\\$2)\\$3"
..
.de Sp
.if n .sp
.if t .sp 0.4
..
.TH T1LINT 1 "LCDF Typetools" "Version \*V"
.SH NAME
t1lint \- check a PostScript Type 1 font for correctness
.SH SYNOPSIS
.B t1lint
\%\fIfont\fR [\fIfont\fR...]
.SH DESCRIPTION
.BR T1lint
checks PostScript Type 1 font programs for correctness.  Any errors or
variances from the specification are reported to standard error.  If there
are no errors, the command prints nothing.  It exits with status 0 if all
fonts were OK, and status 1 otherwise.  If no input files are supplied,
t1lint reads a font from the standard input.
'
.SH OPTIONS
.PD 0
.TP 5
.BR \-q ", " \-\-quiet
Do not generate any error messages.  The only output will be the exit
status.
'
.Sp
.TP 5
.BR \-h ", " \-\-help
Print usage information and exit.
'
.Sp
.TP 5
.BR \-v ", " \-\-version
Print the version number and some short non-warranty information and exit.
.PD
'
.SH "SEE ALSO"
.LP
.M t1disasm 1
.LP
.I "Adobe Type 1 Font Format"
'
.SH AUTHOR
Eddie Kohler (ekohler@gmail.com)
