.TH ALEPH 1 "15 January 2026" "Web2C @VERSION@"
.\"=====================================================================
.if t .ds TX \fRT\\h'-0.10m'\\v'0.17v'E\\v'-0.17v'\\h'-0.06m'X\fP
.if n .ds TX TeX
.\"=====================================================================
.SH NAME
aleph \- extended TeX with Unicode and bidirectional typesetting support
.SH SYNOPSIS
.B aleph
.RI [ options ]
.RI [ \fB&\fPformat ]
\h'.25' [ \fIfile\fP [ \fImore-input\fP ] \h'.5'|\h'.5' [ \fB\e\fP\fImore-input\fP ]
.\"=====================================================================
.SH DESCRIPTION
Run the Aleph typesetter on
.IR file ,
usually creating
.IR file.dvi .
If the file argument has no extension, ".tex" will be appended to it. See
.BR tex (1)
for details of command-line parsing.
.PP
Aleph is no longer being actively developed; see Lua\*(TX for current
activity with Unicode and \*(TX. Aleph is still maintained and
distributed for the sake of supporting existing documents.
.PP
Aleph is essentially the extended \*(TX engine Omega, plus the
.BR etex (1)
extensions. Omega was developed starting in the 1990s to support
Unicode and bidirectional typesetting. To support this, it implements
"Omega translation process" files (\fI.otp\fR), which are compiled into
"Omega compiled process" files (\fI.ocp\fR).
.PP
Omega, and hence Aleph, also has its own extended font formats,
analogous to \*(TX's: Omega metric files (\fI.ofm\fR) and Omega virtual
fonts (\fI.ovf\fR), along with their corresponding human-readable
"property list" forms (\fI.opl\fR and \fI.ovp\fR).
.\"=====================================================================
.SH OPTIONS
See
.BR tex (1).
The -enc, -mltex, -translate-file, and -8bit options are not present in
Aleph.  There are no Aleph-specific options.
.\"=====================================================================
.SH ENVIRONMENT
See
.BR tex (1).
.\"=====================================================================
.SH BUGS
See
.BR tex (1).
.\"=====================================================================
.SH FILES
.TP
.I $TEXMFMAIN/tex/plain/config/aleph.ini
The driver file that builds the Aleph format file, \fIaleph.fmt\fP, in
\*(TX Live.
.\"=====================================================================
.SH "SEE ALSO"
.BR tex (1),
.BR luatex (1).
.br
.BR ofm2opl (1),
.BR opl2ofm (1),
.BR ovf2ovp (1),
.BR ovp2ovf (1).
.br
.BR otangle (1),
.BR odvicopy (1),
.BR odvitype (1).
.PP
Aleph package page on CTAN: https://ctan.org/pkg/aleph
.br
Omega package page on CTAN: https://ctan.org/pkg/omega
.PP
Clearly, this manual page is a bare minimum. Unfortunately,
there is no comprehensive documentation on either Omega or Aleph.
.PP
The Web2c (https://tug.org/web2c) and Kpathsea
(https://tug.org/kpathsea) manuals have brief mentions of the programs
and file formats.
.PP
Perhaps most usefully, a number of articles were published in TUGboat on
their development and usage, mostly by John Plaice and Yannis
Haralambous: https://tug.org/TUGboat.
.PP
Other than that, use the source.
.\"=====================================================================
.SH AUTHORS
\*(TX was created by Donald E. Knuth.
The primary authors of the Aleph enhancements are John Plaice and Yannis
Haralambous, as they are the authors of Omega. The e-\*(TX extensions
were primarily written by Peter Breitenlohner, and added to Aleph by
Giuseppe Bilotta.
.PP
Public discussion list and bug reports: https://lists.tug.org/tex-k
