.TH DVITOMP 1 "16 June 2015" "Web2C @VERSION@"
.\" man page by Jim Van Zandt <jrv@vanzandt.mv.com>
.SH NAME
dvitomp \- convert a TeX DVI file to a MetaPost MPXFILE
.SH SYNOPSIS
.B dvitomp
.RI [ OPTIONS ]
.IR dvifile [ \fB.dvi\fP ]
.RI [ mpxfile [ \fB.mpx\fP ]]
.PP
.B mpost 
.B --dvitomp
.IR dvifile [ \fB.dvi\fP ]
.RI [ mpxfile [ \fB.mpx\fP ]]
.SH DESCRIPTION
\fBdvitomp\fP translates the given \fIdvifile\fP to a MetaPost
MPXFILE.  The default \fImpxfile\fP is the basename of \fIdvifile\fP
extended with
.BR .mpx .
.SH OPTIONS
.IP \fB-help\fP
write usage summary and exit.
.IP \fB-version\fP
output version information and exit.
.SH BUGS
Email bug reports to metapost@tug.org.
