.TH DVITOMP 1 "30 November 2025" "Web2C @VERSION@"
.\" man page originally by Jim Van Zandt
.SH NAME
dvitomp \- convert a TeX DVI file to a MetaPost mpx file
.SH SYNOPSIS
.B dvitomp
.RI [ options ]
.IR dvifile [ \fB.dvi\fP ]
.RI [ mpxfile [ \fB.mpx\fP ]]
.PP
.B mpost 
.B --dvitomp
.IR dvifile [ \fB.dvi\fP ]
.RI [ mpxfile [ \fB.mpx\fP ]]
.SH DESCRIPTION
\fBdvitomp\fP translates the given \fIdvifile\fP to a MetaPost
\fImpxfile\fP.  The default \fImpxfile\fP is the basename of \fIdvifile\fP
extended with
.BR .mpx .
.SH OPTIONS
See
.BR tex (1)
for details of command-line parsing.
.TP
.BI \fB-kpathsea-debug\fP \ bitmask
set path searching debugging flags according to \fIbitmask\fP.
.TP
.BI \fB-progname\fP \ string
set program name to \fIstring\fP.
.PP
The standard
.B -help
and
.B -version
options are also supported.
.SH SEE ALSO
.B dvitomp
is an alias for MetaPost. See
.BR mpost (1).
.PP
Package page on CTAN: https://ctan.org/pkg/dvitomp
.PP
For questions and discussion, email metapost@tug.org.
.br
For detailed bug reports, email mp-implementors@tug.org.
