.TH LATEX-DEV 1 "9 April 2025" "Web2C @VERSION@"
.SH NAME
latex-dev, pdflatex-dev, xelatex-dev, lualatex-dev, dvilualatex-dev, platex-dev, uplatex-dev \- release candidate LaTeX testing
.SH SYNOPSIS
.B latex-dev
.RI [ options ]
.RI [ first-line ]
.\"=====================================================================
.SH DESCRIPTION
.PP
These -dev executables can be used to test upcoming LaTeX releases.
They correspond to new formats which have been tested by the
LaTeX team for stability and usability. Thus, they are not arbitrary
development snapshots; more like release candidates.
.PP
Testing by as many users as possible is desired; indeed, that's the main
reason for these executables to exist. Simply replacing the regular
engine (e.g., pdflatex) with the -dev engine name (pdflatex-dev) in your
invocations is all that should be needed. No changes to source documents
should be required.
.PP
The lualatex-dev format is based on luahbtex, the luatex variant with
harfbuzz enabled for glyph shaping.
.PP
Please report bugs in these -dev versions, like all LaTeX releases,
following the procedure at https://www.latex-project.org/bugs.
.SH "SEE ALSO"
.BR latex (1).
.PP
The LaTeX home page is https://latex-project.org.
