.TH PLTOTF 1 "24 January 2026" "Web2C @VERSION@"
.\"=====================================================================
.if t .ds TX \fRT\\h'-0.10m'\\v'0.17v'E\\v'-0.17v'\\h'-0.06m'X\fP
.if n .ds TX TeX
.ie t .ds OX \fIT\h'-0.17m'\v'+0.21m'E\v'-0.21m'\h'-0.04m'X\fP
.el .ds OX TeX
.\"=====================================================================
.SH NAME
pltotf \- convert a property list (pl) file to TeX font metric (tfm) format
.SH SYNOPSIS
.B pltotf
.RB [ -verbose ]
.IR pl_file [ \fB.pl\fP ]
.RI [ tfm_file [ \fB.tfm\fP ]]
.\"=====================================================================
.SH DESCRIPTION
The
.B pltotf
program translates a (plain text) property list file to a (binary) \*(TX
font metric file. Thus, after editing the property list file, a revised
tfm file can be generated for use with, for example,
.BR tex (1).
.PP
The
.I pl_file
is extended with ".pl" if it lacks a suffix. No path searching is done.
.PP
If no
.I tfm_file
is given, the basename of
.I pl_file
with suffix ".tfm" is used; otherwise,
.I tfm_file
is extended with ".tfm" if it lacks a suffix.
.\"=====================================================================
.SH OPTIONS
See
.BR tex (1)
for details of command-line parsing.
.PP
By default,
.B pltotf
operates silently. With the \fB-v\fP (a.k.a\&. \fB-verbose\fP) option,
some reports are printed on stdout.
.PP
The standard
.B -help
and
.B -version
options are also supported.
.\"=====================================================================
.SH "SEE ALSO"
.BR tftopl (1).
.br
Donald E. Knuth,
.IR "\*(OXware" .
.PP
Font utility topic on CTAN: https://ctan.org/topic/font-util
.br
Package page on CTAN: https://ctan.org/pkg/pltotf
.br
Section in the Web2c manual:
https://tug.org/texinfohtml/web2c.html#pltotf-invocation
.br
Typeset source code, including the PL file format description:
https://ctan.org/pkg/knuth-pdf
.\"=====================================================================
.SH AUTHORS
Donald E. Knuth wrote the program. It was published as
part of the
.I \*(OXware
technical report from Stanford. Howard Trickey, Pavel Curtis, and
Richard Furuta originally ported it to Unix.
.PP
Public discussion list and bug reports: https://lists.tug.org/tex-k
