.TH TIE 1 "7 April 2010" "Web2C @VERSION@"
.\"=====================================================================
.SH NAME
tie \- merge or apply WEB change files
.\"=====================================================================
.SH SYNOPSIS
.B tie
.BR \-c | \-m
.I outputfile masterfile
.IR changefile .\|.\|.
.\"=====================================================================
.SH DESCRIPTION
The
.B tie
program is used to process multiple change files used with the WEB
system for literate programming.  The WEB programs allow to apply
patches to a source file (the
.IR masterfile )
by means of a number of change files (often only a single change file
is allowed).
.B Tie
can be used to either merge up to 32 change files into a single one
or to apply the changes to the
.I masterfile
in order to create a new one.  Output of either the new change file or
the patched master file goes into
.IR outputfile .
.\"=====================================================================
.SH OPTIONS
.TP
.B \-c
Create a single change file from the given
.IR changefile s.
.TP
.B \-m
Create a new master file by applying the given
.IR changefile s.
.\"=====================================================================
.SH ENVIRONMENT
The environment variable WEBINPUTS is used to search for the input files,
or the system default if WEBINPUTS is not set.  See
.BR tex (1)
for the details of the searching.
.\"=====================================================================
.SH "SEE ALSO"
.BR web (1),
.BR ctie (1),
.BR cweb (1).
.\"=====================================================================
.SH "AUTHOR"
Klaus Guntermann, TH Darmstadt, Institut f. Theoretische Informatik.  Man page
by Joachim Schnitter, TH Darmstadt, Phys. Chemie I.
