#! /bin/sh -vx
# $Id$
# Copyright 2026 Sigitas Tolusis <sigitas@vtex.lt>
# You may freely use, modify and/or distribute this file.

_xdvipsk=${BinDir:-.}/xdvipsk${ExeExt:-}
testfile=$1

## to be used without build process directly in Work:
## - copy texk/xdvipsk/testdata/*.test to Work/texk/xdvipsk/testdata/
## - uncomment scrdir
#export srcdir=../../../texk/xdvipsk
## run scripts *.test from Work/texk/xdvipsk/testdata/ 

## set dvi/tex environment from xdvipsk source:
## - texk/xdvipsk/testdata/<test>/
## - texk/xdvipsk/testdata/<test>-gid/
## - texk/xdvipsk/testdata/texmf-test/
##
export TEXMFCNF=../../../texk/kpathsea
export DVIPSFONTS="$srcdir/testdata/{$testfile,$testfile-gid,texmf-test/fonts}//:"
export DVIPSHEADERS="$srcdir/testdata/{$testfile,$testfile-gid,texmf-test/{dvips,fonts}}//:"
export TEXCONFIG="$srcdir/testdata/{$testfile,$testfile-gid,texmf-test/dvips}//:"
export TEXPICTS="$srcdir/testdata/{$testfile,$testfile-gid,texmf-test/images}//:"
export TEXPSHEADERS="$srcdir/testdata/{$testfile,$testfile-gid,texmf-test/{dvips,fonts}}//:"
export TEXFONTMAPS="$srcdir/testdata/{$testfile,$testfile-gid,texmf-test/fonts/map}//:"
export ENCFONTS="$srcdir/testdata/{$testfile,$testfile-gid,texmf-test/{dvips,fonts}}//:"
export TFMFONTS="$srcdir/testdata/{$testfile,$testfile-gid,texmf-test/fonts}//:"
export T1FONTS="$srcdir/testdata/{$testfile,$testfile-gid,texmf-test/fonts}//:"
export OPENTYPEFONTS=":$srcdir/testdata/{$testfile,$testfile-gid,texmf-test/fonts/{opentype,truetype}}//:"
export DVIPSDEBUG=1

## OpenType font tex charcodes encoding (font maps in .xdvipsk catalog - files)
$_xdvipsk -Q1 $srcdir/testdata/$testfile/$testfile.dvi -o ./testdata/$testfile.ps
## The <outputfile>.xdvipsk.log file contains “!!!Success!!!” to indicate xdvipsk success,
## while anything else indicates failure.
## [TODO?] Compare generated PS files with the original ones in the sources for better validation.
diff ./testdata/$testfile.ps.xdvips.log $srcdir/testdata/logs/success.log || exit $2

## OpenType font gid encoding (font maps in dvi file - tex specials)
$_xdvipsk -Q1 $srcdir/testdata/$testfile-gid/$testfile.dvi -o ./testdata/$testfile-gid.ps
diff ./testdata/$testfile-gid.ps.xdvips.log $srcdir/testdata/logs/success.log || exit $3

exit 0
