.\" Copyright (c) 1987-2012 UMD-CS, released under the X11 license;
.\" see README and source files.
.TH DVICONCAT 1
.SH NAME
dviconcat \- concatenate DVI files
.SH SYNOPSIS
.B dviconcat
[
.B \-m
.I magnification
] [
.B \-o
.I outfile
]
.I "list of files"
.SH DESCRIPTION
.I Dviconcat
concatenates the named
.IR file s
(or standard input, if no file names are given)
onto the standard output
or the given
.IR outfile ,
creating a new DVI file
usable by any of the TeX conversion programs,
or even by
.I dviconcat
itself.
.PP
The magnification of the output file
is the same as that of the first input file
unless the
.B \-m
option is given.
When
.I dviconcat
changes the magnification of any input file,
it prints a warning to this effect.
.SH AUTHOR
Chris Torek, University of Maryland
.SH "SEE ALSO"
dviselect(1), latex(1), tex(1)
.br
.I "MC-TeX User's Guide"
.SH BUGS
The program should be called
.IR dvicat ,
but that name was taken (for the driver for the C/A/T typesetter).
