import os

s = [
  "cairo-analysis-surface.o",
  "cairo-arc.o",
  "cairo-array.o",
  "cairo-atomic.o",
  "cairo-base64-stream.o",
  "cairo-base85-stream.o",
  "cairo-bentley-ottmann.o",
  "cairo-bentley-ottmann-rectangular.o",
  "cairo-bentley-ottmann-rectilinear.o",
  "cairo-botor-scan-converter.o",
  "cairo-boxes.o",
  "cairo-boxes-intersect.o",
  "cairo.o",
  "cairo-cache.o",
  "cairo-clip.o",
  "cairo-clip-boxes.o",
  "cairo-clip-polygon.o",
  "cairo-clip-region.o",
  "cairo-clip-surface.o",
  "cairo-color.o",
  "cairo-composite-rectangles.o",
  "cairo-compositor.o",
  "cairo-contour.o",
  "cairo-damage.o",
  "cairo-debug.o",
  "cairo-default-context.o",
  "cairo-device.o",
  "cairo-error.o",
  "cairo-fallback-compositor.o",
  "cairo-fixed.o",
  "cairo-font-face.o",
  "cairo-font-face-twin.o",
  "cairo-font-face-twin-data.o",
  "cairo-font-options.o",
  "cairo-freelist.o",
  "cairo-freed-pool.o",
  "cairo-gstate.o",
  "cairo-hash.o",
  "cairo-hull.o",
  "cairo-image-compositor.o",
  "cairo-image-info.o",
  "cairo-image-source.o",
  "cairo-image-surface.o",
  "cairo-line.o",
  "cairo-lzw.o",
  "cairo-matrix.o",
  "cairo-mask-compositor.o",
  "cairo-mesh-pattern-rasterizer.o",
  "cairo-mempool.o",
  "cairo-misc.o",
  "cairo-mono-scan-converter.o",
  "cairo-mutex.o",
  "cairo-no-compositor.o",
  "cairo-observer.o",
  "cairo-output-stream.o",
  "cairo-paginated-surface.o",
  "cairo-path-bounds.o",
  "cairo-path.o",
  "cairo-path-fill.o",
  "cairo-path-fixed.o",
  "cairo-path-in-fill.o",
  "cairo-path-stroke.o",
  "cairo-path-stroke-boxes.o",
  "cairo-path-stroke-polygon.o",
  "cairo-path-stroke-traps.o",
  "cairo-path-stroke-tristrip.o",
  "cairo-pattern.o",
  "cairo-pdf-interchange.o",
  "cairo-pen.o",
  "cairo-polygon.o",
  "cairo-polygon-intersect.o",
  "cairo-polygon-reduce.o",
  "cairo-raster-source-pattern.o",
  "cairo-recording-surface.o",
  "cairo-rectangle.o",
  "cairo-rectangular-scan-converter.o",
  "cairo-region.o",
  "cairo-rtree.o",
  "cairo-scaled-font.o",
  "cairo-shape-mask-compositor.o",
  "cairo-slope.o",
  "cairo-spans.o",
  "cairo-spans-compositor.o",
  "cairo-spline.o",
  "cairo-stroke-dash.o",
  "cairo-stroke-style.o",
  "cairo-surface.o",
  "cairo-surface-clipper.o",
  "cairo-surface-fallback.o",
  "cairo-surface-observer.o",
  "cairo-surface-offset.o",
  "cairo-surface-snapshot.o",
  "cairo-surface-subsurface.o",
  "cairo-surface-wrapper.o",
  "cairo-tag-attributes.o",
  "cairo-tag-stack.o",
  "cairo-time.o",
  "cairo-tor-scan-converter.o",
  "cairo-tor22-scan-converter.o",
  "cairo-clip-tor-scan-converter.o",
  "cairo-toy-font-face.o",
  "cairo-traps.o",
  "cairo-tristrip.o",
  "cairo-traps-compositor.o",
  "cairo-unicode.o",
  "cairo-user-font.o",
  "cairo-version.o",
  "cairo-wideint.o",
  "cairo-pdf-surface.o",
  "cairo-pdf-operators.o",
  "cairo-pdf-shading.o",
  "cairo-cff-subset.o",
  "cairo-scaled-font-subsets.o",
  "cairo-truetype-subset.o",
  "cairo-type1-fallback.o",
  "cairo-type1-glyph-names.o",
  "cairo-type1-subset.o",
  "cairo-type3-glyph-surface.o",
  "cairo-deflate-stream.o"
]

CFLAGS = "-c -Wno-attributes -I. -I../../texlive/libs/cairo/cairo-src/src -I../../texlive/libs/zlib/include -I../../texlive/libs/pixman/include -DHAVE_CONFIG_H -DCAIRO_NO_MUTEX"
PREFIX = "../../texlive/libs/cairo/cairo-src/src/"

makefile = open("Makefile", "w")
makefile.write("CC = gcc\n")
makefile.write("CFLAGS = %s\n" % CFLAGS)
makefile.write("objects = %s\n" % " ".join(s))
makefile.write("libcairo.a: $(objects)\n")
makefile.write("\t ar cru libcairo.a $(objects)\n")
for i in s:
  makefile.write("%s : %s%s\n" % (i, PREFIX, i.replace(".o", ".c")))
  makefile.write("\t $(CC) $(CFLAGS) %s%s\n" % (PREFIX, i.replace(".o", ".c")))
makefile.write("clean:\n")
makefile.write("\trm $(wildcard *.o *.a)\n")
makefile.write("test:\n")
makefile.write("\t$(CC) -I. -I../../texlive/libs/cairo/cairo-src/src -o test test.c libcairo.a ../libpixman.a ../libz.a -lm\n")
makefile.close()
