---
%\input musixlyr
%\special{papersize=297mm,420mm}%
---
%|
%<?xmlversion="1.0"encoding="UTF-8"?>
%<!DOCTYPEscore-partwisePUBLIC"-//Recordare//DTDMusicXML3.0Partwise//EN""http://www.musicxml.org/dtds/partwise.dtd">
%An die ferne Geliebte (Page 1)
%% work number : Op. 98
%Ludwig van Beethoven
%
%
%Part P1 : Voice
%Part P2 : Acoustic Grand Piano
%
%
% nv, -noinst, nostaves per instrument
 3 -2 2 1
% mtrnuml,mtrdenl,mtrnmp,mtrdnp,xmtrnum0,isig
 3 4 3 4 0 -3
%
% npages,nsyst,musicsize,fracindent 
 0 5 16 0.07
Piano
Voice
btt
./
Tt
An die ferne Geliebte (Page 1)
Tc
Ludwig van Beethoven
Abepl
\\input musixper\
%%w277m
%%h390m

% ( 2| 2| 3) 1
 \PED\ e42u ze3 Ct \DEP\ (Bl g44u f44u )B /
% ( 2| 1| 1) 1
 b43u Dp ze4 zg4 zb4 (Bu b44l a44u )B /
% ( 1| 1| 1) 1
 \zcharnote{12}{Ziemlich langsam und mit Ausdruck No. 1}\ r4 b44l b44l /
% ( 2| 2| 3) 2
 e44u Cb \PED\ e42u ze3 \DEP\ r4 /
% ( 2| 1| 1) 2
 g44u g43u ze4 zg4 r4 /
% ( 1| 1| 1) 2
 b4d4l c85l [l d85l e85l ] /
% ( 2| 2| 3) 3
 r4 \PED\ c42u zc3 \DEP\ r8 b81u zb2 /
% ( 2| 1| 1) 3
 r4 g43u zc4 ze4 zg4 r8 g83u ze4 zg4 /
% ( 1| 1| 1) 3
 e45l g84u r8 [u a84u g84u ] /
% ( 2| 2| 3) 4
 a41u za2 (Cl a41u za2 a41nu za2n /
% ( 2| 1| 1) 4
 (Bu [u f84u a84u ] c45u )B c45u //
% ( 2| 1| 2) 4
 c44l c44l zf4 (Bl c44l ze4 {0u zf4 /
% ( 1| 1| 1) 4
 [u f84u a84u ] c45l c45l /
% ( 2| 2| 3) 5
 b41u )C zb2 (Bu d43l e43l /
% ( 2| 1| 1) 5
 r4b (Du b4d4u c85u //
% ( 2| 1| 2) 5
 d44u )B zf4 }0 f44l g44l /
% ( 1| 1| 1) 5
 f44u b4d4l c85l /
% ( 2| 2| 3) 6
 c43u c44u )B r4b //
% ( 2| 2| 4) 6
 c23l d43l zb3 zd4 /
% ( 2| 1| 1) 6
 b44u a44nu )D (Cu [u a84fu b84u )C ] //
% ( 2| 1| 2) 6
 e24l zg4f f44l /
% ( 1| 1| 1) 6
 b44l a44nu [u a84fu b84u ] /
% ( 2| 2| 3) 7
 (Bu b43u e44u )B r4b //
% ( 2| 2| 4) 7
 e23l g42l ze3 zg3 /
% ( 2| 1| 1) 7
 (Bl f44u za4 g44nu )B D< [u e84u zb4 ze5 e84u ] zb4 zd5 D<+0+3 /
% ( 1| 1| 1) 7
 a44u g44u [l e85l d85l ] /
% ( 2| 2| 3) 8
 a42l ze3 za3 [u a82u ze3 za3 b82u ze3 zb3 b82u zb3 b81u ] zb2 /
% ( 2| 1| 1) 8
 (Bu e44u D> zb4 zd5 [u e84u )B za4 zc5 D>+0+3 e84u zg4 zb4 d84u zf4 za4 a83u ] zd4 zf4 /
% ( 1| 1| 1) 8
 (Bu d45l [l c85l )B b84l ] [u a84u f84u ] /
% ( 2| 2| 3) 9
 e42u ze3 e23l zg3 zb3 ze4 /
% ( 2| 1| 1) 9
 g43u ze4 \zcharnote{12}{Ausdrucksvoll espressivo}\ (Bu G1m1xb4 D> b4d5l )B D>+0+3 e85l /
% ( 1| 1| 1) 9
 e44u r4 r4 /
% ( 2| 2| 3) 10
 e43l zf3 za3 zd4 e4d3l zf3 za3 zb3 zd4 (Cu d84l /
% ( 2| 1| 1) 10
 d45l (Bu G1m1xb4 D> \zcharnote{-6}{dim.}\ b4d5l )B D>+0+3 (Bu d85l /
% ( 1| 1| 1) 10
 rp /
% ( 2| 2| 3) 11
 [l f84l f83l )C za3 (Bu f83l za3 e83nl zg3 g83l zb3 f83l )B ] za3 /
% ( 2| 1| 1) 11
 [u f85u f84u )B za4 (Bl f84u za4 e84nu zg4 g84u zb4 f84u )B ] za4 /
% ( 1| 1| 1) 11
 r4 b44l b44l /
% ( 2| 2| 3) 12
 e83fl zg3 r8 [l e83l r1 e13l ] e82u r8 /
% ( 2| 1| 1) 12
 e84fu zg4 r8 [u b83u zg4 r1 b13u ] zg4 b83u zg4 r8 /
% ( 1| 1| 1) 12
 b4d4l c85l [l d85l e85l ] /
% ( 2| 2| 3) 13
 r4 [l c84l r1 c14l ] [u c83u b82u ] /
% ( 2| 1| 1) 13
 r4 [u e84u zg4 r1 e14u ] zg4 [u e84u za4 ze5 e84u ] zg4 /
% ( 1| 1| 1) 13
 e45l g84u r8 [u a84u g84u ] /
% ( 2| 2| 3) 14
 a82u r8 [l a83l r1 a12l ] za3 a42nl za3n /
% ( 2| 1| 1) 14
 c84u zf4 r8 [u c84u zf4 r1 c14u ] zf4 c84u ze4 zf4 zc5 r8 /
% ( 1| 1| 1) 14
 [u f84u a84u ] c45l c45l /
% ( 2| 2| 3) 15
 b82l zb3 r8 [l d83l zb3 r1 d13l ] zb3 e83l zb3 r8 /
% ( 2| 1| 1) 15
 d84u zf4 r8 [u f84u zb4 r1 f14u ] zb4 g84u zb4 r8 /
% ( 1| 1| 1) 15
 f44u b4d4l c85l /
