---
%\input musixlyr
%\special{papersize=297mm,420mm}%
---
%|
%<?xmlversion="1.0"encoding="UTF-8"?>
%<!DOCTYPEscore-partwisePUBLIC"-//Recordare//DTDMusicXML3.0Partwise//EN""http://www.musicxml.org/dtds/partwise.dtd">
%Ave Maria (Ellen's Gesang III) - Page 1
%% work number : D. 839
%Franz Schubert
%
%
%Part P1 : Choir Aahs
%Part P2 : Grand Piano
%
%
% nv, -noinst, nostaves per instrument
 3 -2 2 1
% mtrnuml,mtrdenl,mtrnmp,mtrdnp,xmtrnum0,isig
 4 4 0 6 0 -2
%
% npages,nsyst,musicsize,fracindent 
 0 5 16 0.07
Grand Piano
Choir Aahs
btt
./
Tt
Ave Maria (Ellen's Gesang III) - Page 1
Tc
Franz Schubert
Abepl
\\input musixper\
%%w277m
%%h390m

% ( 2| 2| 2) 1
 \zcharnote{-6}{col Pedale}\ b81u zb2 r8 b81u zb2 r8 b81u zb2 r8 b81u zb2 r8 /
% ( 2| 1| 1) 1
 \zcharnote{12}{Sehr langsam}\ r4x6 Dpp (Bl d4u zf4 f4u zb4 b4u o> zd5 f4u zb4 d4u )B zf4 r4x6 (Bl d4u 
zf4 f4u zb4 b4u o> zd5 f4u zb4 d4u )B zf4 D< r4x6 (Bu f4l zb4 b4l zd5 d5l o> zf5 b4l zd5 f4l )B zb4 r4x6 
(Bu a4fl zd5 d5l zf5 f5l o> za5f d5l zf5 D<+0+3 a4l )B zd5 /
% ( 1| 1| 1) 1
 rp /
% ( 2| 2| 2) 2
 b81u zb2 r8 b81u zb2 r8 b81u zb2 r8 b81u zb2 r8 /
% ( 2| 1| 1) 2
 r4x6 D> (Bu g4l zb4 b4l ze5 e5l o> zg5 b4l ze5 g4l )B zb4 r4x6 (Bu g4fl za4n a4l ze5 e5l o> zg5f a4l 
ze5 D>+0+3 g4l )B za4 r4x6 (Bu f4l zb4 b4l zd5 d5l o> zf5 b4l zd5 f4l )B zb4 r4x6 (Bl d4u zf4 f4u zb4 
b4u o> zd5 f4u zb4 d4u )B zf4 /
% ( 1| 1| 1) 2
 rp /
% ( 2| 2| 2) 3
 Rl b81u zb2 r8 g81u zg2 r8 f81u zf2 r8 f81u zf2 r8 /
% ( 2| 1| 1) 3
 r4x6 d4u zf4 f4u zb4 b4u zd5 f4u zb4 d4u zf4 r4x6 d4u ze4n e4u zb4 b4u zd5 e4u zb4 d4u ze4 r4x6 d4u 
zf4 f4u zb4 b4u zd5 f4u zb4 d4u zf4 r4x6 e4fu za4 a4u zc5 c5u ze5 a4u zc5 e4u za4 /
% ( 1| 1| 1) 3
 b4d4l [u a14u b14u ] (Bu d4dd5l c15l )B /
% ( 2| 2| 2) 4
 g81u zg2 r8 g81u zg2 r8 e81u ze2 r8 f81u zf2 r8 /
% ( 2| 1| 1) 4
 r4x6 d4u zg4 g4u zb4 b4u zd5 g4u zb4 d4u zg4 r4x6 d4u zg4 g4u zb4 b4u zd5 g4u zb4 d4u zg4 r4x6 e4u zg4 
g4u zc5 c5u ze5 g4u zc5 e4u zg4 r4x6 e4u zf4 f4u za4 a4u zc5 f4u za4 e4u zf4 /
% ( 1| 1| 1) 4
 b44l r4 (Bu c45l G2m3d5 c5 [u b14u a14u )B (Bl g14u a14u )B ] /
% ( 2| 2| 2) 5
 b81u zb2 r8 b81u zb2 r8 b81u zb2 r8 b81u zb2 r8 /
% ( 2| 1| 1) 5
 r4x6 d4u zf4 f4u zb4 b4u zd5 f4u zb4 d4u zf4 r4x6 d4u zf4 f4u zb4 b4u zd5 f4u zb4 d4u zf4 D< r4x6 d4u 
zf4s f4u zb4 b4u zd5 f4u zb4 d4u zf4 r4x6 d4u zg4 g4u zb4 b4u zd5 g4u zb4 D<+0+3 d4u zg4 /
% ( 1| 1| 1) 5
 b44l r8 d85l [l d8d5l (Bu c35l b34l )B ] [u a14u g14u ] [l d15l e15nl ] /
% ( 2| 2| 2) 6
 a81u za2 r8 a81u za2 r8 f81su zf2s r8 f81u zf2 r8 /
% ( 2| 1| 1) 6
 r4x6 D> e4nu zg4 g4u zb4 b4u zd5 g4u zb4 e4u zg4 r4x6 e4u zg4 g4u za4 a4u zc5s g4u za4 e4u zg4 D>+0+3 
r4x6 e4fu za4 a4u zc5n c5u ze5 a4u zc5 e4u za4 r4x6 e4u za4 a4u zc5 c5u ze5 a4u zc5 e4u za4 /
% ( 1| 1| 1) 6
 d45l [l c8d5sl a14l ] [l c8d5nl b14l ] (Bu [l a84x3 c5l )B d5l (Bu e85x3 c5l )B a4l ] /
% ( 2| 2| 2) 7
 g81u zg2 r8 g81u zg2 r8 a81u za2 r8 d82u zd3 r8 /
% ( 2| 1| 1) 7
 r4x6 d4u zg4 g4u zb4 b4u zd5 g4u zb4 d4u zg4 r4x6 d4u ze4n e4u zb4 b4u zd5 e4u zb4 d4u ze4 r4x6 c4u 
zf4 f4u za4 a4u zc5 f4u za4 c4u zf4 r4x6 f4l zg4 g4l zb4n b4l zf5 g4l zb4 f4l zg4 /
% ( 1| 1| 1) 7
 b4d4l (Bu [l d15l c15l )B ] [l c8d5l a14l ] (Bu [l g84x3 b4nl )B d5l ] (Bu [l f85x3 d5l )B b4l ] /
% ( 2| 2| 2) 8
 c82u zc3 r8 c82u zc3 r8 f82u zf3 r8 f82u zf3 r8 /
% ( 2| 1| 1) 8
 r4x6 f4l za4 a4l zc5 c5l zf5 a4l zc5 f4l za4 r4x6 e4nu zb4 b4u zc5 c5u ze5n b4u zc5 e4u zb4 r4x6 f4l 
za4 a4l zc5 c5l zf5 a4l zc5 f4l za4 r4x6 f4l za4 a4l zc5 c5l zf5 a4l zc5 f4l za4 /
% ( 1| 1| 1) 8
 (Bu {0 c45l [u c45x6 }0 g4u a4u b4fu G2m2c5 b4 a4u g4u )B ] f44u r8 f84u /
