#! /bin/sh

# Copyright (C) 1994-2015  Werner Lemberg <wl@gnu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program in doc/COPYING; if not, write to the Free
# Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
# MA 02110-1301 USA

n=1
argv=

# get last argument
while test 1 -lt $#; do
  eval argv$n=\$1
  argv="$argv \"\$argv$n\""
  n=`expr $n + 1`
  shift
done

# replace extension with .cjk or append .cjk if there is no extension
tex=$1
case $tex in
""|*.cjk)
  echo >&2 "Usage: $0 [options] latex-file"
  exit 1;;
*)
  aux=`expr "X$tex" : 'X\(.*\)\.[^/]*$' \| "X$tex" : 'X\(.*\)'`.cjk;;
esac

sjisconv < "$tex" > "$aux" && eval pdflatex "$argv" "\$aux"

# EOF
