.TH LIBOTF-CONFIG "1" "January 2011" "libotf-config 0.9.12" "User Commands"
.SH NAME
libotf\-config \- Print compile and link options of the otf library
.SH SYNOPSIS
.B libotf-config
[ \fI\-\-cflags\fR | \fI\-\-libs\fR | \fI\-\-version\fR ]
.SH DESCRIPTION
.PP
The shell script libotf\-config prints compile and link options for a program that uses the otf library.
.PP
The arguments are as follows:
.TP
\-\-cflags
.br
 Print compile option (e.g. \-I/usr/local/include)
.TP
\-\-libs
.br
 Print link option (e.g. \-L/usr/local/lib \-lotf)
.TP
\-\-version
.br
 Print version number of the otf library.
.SH AUTHOR
Harshula Jayasuriya <harshula@debian.org>
.SH COPYRIGHT
Copyright (C) 2011 Harshula Jayasuriya
.br
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
