# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/windows/custMatTransform.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 320)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(500, 320))
        Dialog.setMaximumSize(QtCore.QSize(500, 320))
        Dialog.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/android-expand.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(False)
        self.centralFrame = QtWidgets.QFrame(Dialog)
        self.centralFrame.setGeometry(QtCore.QRect(20, 20, 461, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralFrame.sizePolicy().hasHeightForWidth())
        self.centralFrame.setSizePolicy(sizePolicy)
        self.centralFrame.setBaseSize(QtCore.QSize(0, 0))
        self.centralFrame.setObjectName("centralFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralFrame)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridFrame = QtWidgets.QFrame(self.centralFrame)
        self.gridFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.lineMat00 = QtWidgets.QLineEdit(self.gridFrame)
        self.lineMat00.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineMat00.setObjectName("lineMat00")
        self.gridLayout.addWidget(self.lineMat00, 1, 0, 1, 1)
        self.lineMat11 = QtWidgets.QLineEdit(self.gridFrame)
        self.lineMat11.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineMat11.setObjectName("lineMat11")
        self.gridLayout.addWidget(self.lineMat11, 2, 1, 1, 1)
        self.lineMat10 = QtWidgets.QLineEdit(self.gridFrame)
        self.lineMat10.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineMat10.setObjectName("lineMat10")
        self.gridLayout.addWidget(self.lineMat10, 2, 0, 1, 1)
        self.lineMat01 = QtWidgets.QLineEdit(self.gridFrame)
        self.lineMat01.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineMat01.setObjectName("lineMat01")
        self.gridLayout.addWidget(self.lineMat01, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.gridFrame)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.gridFrame_2 = QtWidgets.QFrame(self.centralFrame)
        self.gridFrame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.gridFrame_2.setObjectName("gridFrame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridFrame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineMatTy = QtWidgets.QLineEdit(self.gridFrame_2)
        self.lineMatTy.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineMatTy.setObjectName("lineMatTy")
        self.gridLayout_2.addWidget(self.lineMatTy, 2, 1, 1, 1)
        self.lineMatTx = QtWidgets.QLineEdit(self.gridFrame_2)
        self.lineMatTx.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineMatTx.setObjectName("lineMatTx")
        self.gridLayout_2.addWidget(self.lineMatTx, 1, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.gridFrame_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralFrame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.imgPreview = QtWidgets.QLabel(self.centralFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgPreview.sizePolicy().hasHeightForWidth())
        self.imgPreview.setSizePolicy(sizePolicy)
        self.imgPreview.setMinimumSize(QtCore.QSize(150, 150))
        self.imgPreview.setBaseSize(QtCore.QSize(300, 300))
        self.imgPreview.setFrameShape(QtWidgets.QFrame.Box)
        self.imgPreview.setText("")
        self.imgPreview.setObjectName("imgPreview")
        self.verticalLayout_2.addWidget(self.imgPreview)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.lblAnchor = QtWidgets.QLabel(self.centralFrame)
        self.lblAnchor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAnchor.setObjectName("lblAnchor")
        self.verticalLayout_3.addWidget(self.lblAnchor)
        self.lblCoordsMode = QtWidgets.QLabel(self.centralFrame)
        self.lblCoordsMode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCoordsMode.setObjectName("lblCoordsMode")
        self.verticalLayout_3.addWidget(self.lblCoordsMode)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.btnReset = QtWidgets.QPushButton(self.centralFrame)
        self.btnReset.setObjectName("btnReset")
        self.horizontalLayout_2.addWidget(self.btnReset)
        self.btnCancel = QtWidgets.QPushButton(self.centralFrame)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_2.addWidget(self.btnCancel)
        self.btnAccept = QtWidgets.QPushButton(self.centralFrame)
        self.btnAccept.setObjectName("btnAccept")
        self.horizontalLayout_2.addWidget(self.btnAccept)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Set Custom Transformation"))
        self.label.setText(_translate("Dialog", "Transformation Matrix"))
        self.lineMat00.setText(_translate("Dialog", "1"))
        self.lineMat11.setText(_translate("Dialog", "1"))
        self.lineMat10.setText(_translate("Dialog", "0"))
        self.lineMat01.setText(_translate("Dialog", "0"))
        self.label_3.setText(_translate("Dialog", "Translation"))
        self.lineMatTy.setText(_translate("Dialog", "0"))
        self.lineMatTx.setText(_translate("Dialog", "0"))
        self.label_2.setText(_translate("Dialog", "Preview:"))
        self.imgPreview.setToolTip(_translate("Dialog", "Shows a red square if transformation determinant is negative."))
        self.lblAnchor.setText(_translate("Dialog", "Anchor: Top Left"))
        self.lblCoordsMode.setText(_translate("Dialog", "Coordinates: Global"))
        self.btnReset.setText(_translate("Dialog", "Reset"))
        self.btnCancel.setText(_translate("Dialog", "Cancel"))
        self.btnAccept.setText(_translate("Dialog", "Accept"))
import icons_rc
