# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'window1.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFormLayout, QFrame,
    QGridLayout, QHBoxLayout, QLabel, QLayout,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QSpacerItem, QStatusBar,
    QVBoxLayout, QWidget)
from xasyicons import icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1000, 600)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionManual = QAction(MainWindow)
        self.actionManual.setObjectName(u"actionManual")
        self.actionSettings = QAction(MainWindow)
        self.actionSettings.setObjectName(u"actionSettings")
        self.actionPause = QAction(MainWindow)
        self.actionPause.setObjectName(u"actionPause")
        self.actionSaveAs = QAction(MainWindow)
        self.actionSaveAs.setObjectName(u"actionSaveAs")
        self.actionEnterCommand = QAction(MainWindow)
        self.actionEnterCommand.setObjectName(u"actionEnterCommand")
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        self.actionUndo.setEnabled(False)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        self.actionRedo.setEnabled(False)
        self.actionShow_Grid = QAction(MainWindow)
        self.actionShow_Grid.setObjectName(u"actionShow_Grid")
        self.actionShow_Local_Grid = QAction(MainWindow)
        self.actionShow_Local_Grid.setObjectName(u"actionShow_Local_Grid")
        self.actionTransform = QAction(MainWindow)
        self.actionTransform.setObjectName(u"actionTransform")
        self.actionExportAsymptote = QAction(MainWindow)
        self.actionExportAsymptote.setObjectName(u"actionExportAsymptote")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionClearRecent = QAction(MainWindow)
        self.actionClearRecent.setObjectName(u"actionClearRecent")
        self.actionNewFile = QAction(MainWindow)
        self.actionNewFile.setObjectName(u"actionNewFile")
        self.actionExportToAsy = QAction(MainWindow)
        self.actionExportToAsy.setObjectName(u"actionExportToAsy")
        self.actionKeymaps = QAction(MainWindow)
        self.actionKeymaps.setObjectName(u"actionKeymaps")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMouseTracking(True)
        self.horizontalLayout_4 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.mainWidget = QWidget(self.centralwidget)
        self.mainWidget.setObjectName(u"mainWidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.mainWidget.sizePolicy().hasHeightForWidth())
        self.mainWidget.setSizePolicy(sizePolicy1)
        self.mainWidget.setMouseTracking(True)
        self.verticalLayout = QVBoxLayout(self.mainWidget)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.menuFrame = QFrame(self.mainWidget)
        self.menuFrame.setObjectName(u"menuFrame")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.menuFrame.sizePolicy().hasHeightForWidth())
        self.menuFrame.setSizePolicy(sizePolicy2)
        self.menuFrame.setFrameShape(QFrame.NoFrame)
        self.horizontalLayout = QHBoxLayout(self.menuFrame)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.btnUndo = QPushButton(self.menuFrame)
        self.btnUndo.setObjectName(u"btnUndo")
        self.btnUndo.setEnabled(False)
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.btnUndo.sizePolicy().hasHeightForWidth())
        self.btnUndo.setSizePolicy(sizePolicy3)
        self.btnUndo.setMaximumSize(QSize(25, 25))
        self.btnUndo.setBaseSize(QSize(32, 32))
        icon = QIcon()
        icon.addFile(u":/icons/undo.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnUndo.setIcon(icon)
        self.btnUndo.setIconSize(QSize(16, 16))
        self.btnUndo.setFlat(True)

        self.horizontalLayout.addWidget(self.btnUndo)

        self.btnRedo = QPushButton(self.menuFrame)
        self.btnRedo.setObjectName(u"btnRedo")
        self.btnRedo.setEnabled(False)
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.btnRedo.sizePolicy().hasHeightForWidth())
        self.btnRedo.setSizePolicy(sizePolicy4)
        self.btnRedo.setMaximumSize(QSize(25, 25))
        self.btnRedo.setBaseSize(QSize(32, 32))
        icon1 = QIcon()
        icon1.addFile(u":/icons/redo.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnRedo.setIcon(icon1)
        self.btnRedo.setIconSize(QSize(16, 16))
        self.btnRedo.setFlat(True)

        self.horizontalLayout.addWidget(self.btnRedo)

        self.btnLoadFile = QPushButton(self.menuFrame)
        self.btnLoadFile.setObjectName(u"btnLoadFile")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.btnLoadFile.sizePolicy().hasHeightForWidth())
        self.btnLoadFile.setSizePolicy(sizePolicy5)
        self.btnLoadFile.setMaximumSize(QSize(25, 25))
        self.btnLoadFile.setBaseSize(QSize(32, 32))
        icon2 = QIcon()
        icon2.addFile(u":/icons/android-folder-open.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnLoadFile.setIcon(icon2)
        self.btnLoadFile.setIconSize(QSize(16, 16))
        self.btnLoadFile.setFlat(True)

        self.horizontalLayout.addWidget(self.btnLoadFile)

        self.btnSave = QPushButton(self.menuFrame)
        self.btnSave.setObjectName(u"btnSave")
        sizePolicy4.setHeightForWidth(self.btnSave.sizePolicy().hasHeightForWidth())
        self.btnSave.setSizePolicy(sizePolicy4)
        self.btnSave.setMaximumSize(QSize(25, 25))
        self.btnSave.setBaseSize(QSize(32, 32))
        icon3 = QIcon()
        icon3.addFile(u":/icons/save.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnSave.setIcon(icon3)
        self.btnSave.setIconSize(QSize(16, 16))
        self.btnSave.setFlat(True)

        self.horizontalLayout.addWidget(self.btnSave)

        self.btnViewCode = QPushButton(self.menuFrame)
        self.btnViewCode.setObjectName(u"btnViewCode")
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Maximum)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.btnViewCode.sizePolicy().hasHeightForWidth())
        self.btnViewCode.setSizePolicy(sizePolicy6)
        self.btnViewCode.setMaximumSize(QSize(24, 24))
        self.btnViewCode.setBaseSize(QSize(20, 20))
        icon4 = QIcon()
        icon4.addFile(u":/icons/code.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnViewCode.setIcon(icon4)
        self.btnViewCode.setIconSize(QSize(16, 16))
        self.btnViewCode.setFlat(True)

        self.horizontalLayout.addWidget(self.btnViewCode)

        self.btnQuickScreenshot = QPushButton(self.menuFrame)
        self.btnQuickScreenshot.setObjectName(u"btnQuickScreenshot")
        sizePolicy5.setHeightForWidth(self.btnQuickScreenshot.sizePolicy().hasHeightForWidth())
        self.btnQuickScreenshot.setSizePolicy(sizePolicy5)
        self.btnQuickScreenshot.setMaximumSize(QSize(25, 25))
        self.btnQuickScreenshot.setBaseSize(QSize(32, 32))
        icon5 = QIcon()
        icon5.addFile(u":/icons/android-camera.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnQuickScreenshot.setIcon(icon5)
        self.btnQuickScreenshot.setIconSize(QSize(16, 16))
        self.btnQuickScreenshot.setFlat(True)

        self.horizontalLayout.addWidget(self.btnQuickScreenshot)

        self.horizontalSpacer_3 = QSpacerItem(20, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_3)

        self.btnDrawAxes = QPushButton(self.menuFrame)
        self.btnDrawAxes.setObjectName(u"btnDrawAxes")
        sizePolicy6.setHeightForWidth(self.btnDrawAxes.sizePolicy().hasHeightForWidth())
        self.btnDrawAxes.setSizePolicy(sizePolicy6)
        self.btnDrawAxes.setMaximumSize(QSize(25, 25))
        self.btnDrawAxes.setBaseSize(QSize(32, 32))
        font = QFont()
        font.setFamilies([u"Roboto"])
        font.setBold(True)
        self.btnDrawAxes.setFont(font)
        icon6 = QIcon()
        icon6.addFile(u":/icons/plus-round.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnDrawAxes.setIcon(icon6)
        self.btnDrawAxes.setIconSize(QSize(16, 16))
        self.btnDrawAxes.setCheckable(True)
        self.btnDrawAxes.setChecked(True)
        self.btnDrawAxes.setFlat(True)

        self.horizontalLayout.addWidget(self.btnDrawAxes)

        self.btnDrawGrid = QPushButton(self.menuFrame)
        self.btnDrawGrid.setObjectName(u"btnDrawGrid")
        sizePolicy6.setHeightForWidth(self.btnDrawGrid.sizePolicy().hasHeightForWidth())
        self.btnDrawGrid.setSizePolicy(sizePolicy6)
        self.btnDrawGrid.setMaximumSize(QSize(25, 25))
        self.btnDrawGrid.setBaseSize(QSize(32, 32))
        self.btnDrawGrid.setFont(font)
        icon7 = QIcon()
        icon7.addFile(u":/icons/grid.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnDrawGrid.setIcon(icon7)
        self.btnDrawGrid.setIconSize(QSize(16, 16))
        self.btnDrawGrid.setCheckable(True)
        self.btnDrawGrid.setChecked(False)
        self.btnDrawGrid.setFlat(True)

        self.horizontalLayout.addWidget(self.btnDrawGrid)

        self.btnSetZoom = QPushButton(self.menuFrame)
        self.btnSetZoom.setObjectName(u"btnSetZoom")
        sizePolicy5.setHeightForWidth(self.btnSetZoom.sizePolicy().hasHeightForWidth())
        self.btnSetZoom.setSizePolicy(sizePolicy5)
        self.btnSetZoom.setMaximumSize(QSize(25, 25))
        self.btnSetZoom.setBaseSize(QSize(32, 32))
        icon8 = QIcon()
        icon8.addFile(u":/icons/magnifying-glass.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnSetZoom.setIcon(icon8)
        self.btnSetZoom.setIconSize(QSize(16, 16))
        self.btnSetZoom.setFlat(True)

        self.horizontalLayout.addWidget(self.btnSetZoom)

        self.btnPanCenter = QPushButton(self.menuFrame)
        self.btnPanCenter.setObjectName(u"btnPanCenter")
        sizePolicy5.setHeightForWidth(self.btnPanCenter.sizePolicy().hasHeightForWidth())
        self.btnPanCenter.setSizePolicy(sizePolicy5)
        self.btnPanCenter.setMaximumSize(QSize(25, 25))
        self.btnPanCenter.setBaseSize(QSize(32, 32))
        icon9 = QIcon()
        icon9.addFile(u":/icons/center.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnPanCenter.setIcon(icon9)
        self.btnPanCenter.setIconSize(QSize(16, 16))
        self.btnPanCenter.setFlat(True)

        self.horizontalLayout.addWidget(self.btnPanCenter)

        self.btnResetPan = QPushButton(self.menuFrame)
        self.btnResetPan.setObjectName(u"btnResetPan")
        sizePolicy5.setHeightForWidth(self.btnResetPan.sizePolicy().hasHeightForWidth())
        self.btnResetPan.setSizePolicy(sizePolicy5)
        self.btnResetPan.setMaximumSize(QSize(25, 25))
        self.btnResetPan.setBaseSize(QSize(32, 32))
        icon10 = QIcon()
        icon10.addFile(u":/icons/centerorigin.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnResetPan.setIcon(icon10)
        self.btnResetPan.setIconSize(QSize(16, 16))
        self.btnResetPan.setFlat(True)

        self.horizontalLayout.addWidget(self.btnResetPan)

        self.btnAlignX = QPushButton(self.menuFrame)
        self.btnAlignX.setObjectName(u"btnAlignX")
        sizePolicy6.setHeightForWidth(self.btnAlignX.sizePolicy().hasHeightForWidth())
        self.btnAlignX.setSizePolicy(sizePolicy6)
        self.btnAlignX.setMaximumSize(QSize(32, 25))
        self.btnAlignX.setBaseSize(QSize(32, 32))
        self.btnAlignX.setFont(font)
        self.btnAlignX.setIconSize(QSize(16, 16))
        self.btnAlignX.setCheckable(True)
        self.btnAlignX.setFlat(True)

        self.horizontalLayout.addWidget(self.btnAlignX)

        self.btnAlignY = QPushButton(self.menuFrame)
        self.btnAlignY.setObjectName(u"btnAlignY")
        sizePolicy6.setHeightForWidth(self.btnAlignY.sizePolicy().hasHeightForWidth())
        self.btnAlignY.setSizePolicy(sizePolicy6)
        self.btnAlignY.setMaximumSize(QSize(32, 25))
        self.btnAlignY.setBaseSize(QSize(32, 32))
        self.btnAlignY.setFont(font)
        self.btnAlignY.setIconSize(QSize(16, 16))
        self.btnAlignY.setCheckable(True)
        self.btnAlignY.setFlat(True)

        self.horizontalLayout.addWidget(self.btnAlignY)

        self.horizontalSpacer_6 = QSpacerItem(20, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_6)

        self.btnSelectEdit = QPushButton(self.menuFrame)
        self.btnSelectEdit.setObjectName(u"btnSelectEdit")
        self.btnSelectEdit.setEnabled(True)
        sizePolicy6.setHeightForWidth(self.btnSelectEdit.sizePolicy().hasHeightForWidth())
        self.btnSelectEdit.setSizePolicy(sizePolicy6)
        self.btnSelectEdit.setMaximumSize(QSize(25, 25))
        icon11 = QIcon()
        icon11.addFile(u":/icons/edit.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnSelectEdit.setIcon(icon11)
        self.btnSelectEdit.setIconSize(QSize(16, 16))
        self.btnSelectEdit.setCheckable(True)
        self.btnSelectEdit.setFlat(True)

        self.horizontalLayout.addWidget(self.btnSelectEdit)

        self.btnDeleteMode = QPushButton(self.menuFrame)
        self.btnDeleteMode.setObjectName(u"btnDeleteMode")
        self.btnDeleteMode.setEnabled(True)
        sizePolicy6.setHeightForWidth(self.btnDeleteMode.sizePolicy().hasHeightForWidth())
        self.btnDeleteMode.setSizePolicy(sizePolicy6)
        self.btnDeleteMode.setMaximumSize(QSize(25, 25))
        self.btnDeleteMode.setBaseSize(QSize(32, 32))
        icon12 = QIcon()
        icon12.addFile(u":/icons/android-delete.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnDeleteMode.setIcon(icon12)
        self.btnDeleteMode.setIconSize(QSize(16, 16))
        self.btnDeleteMode.setCheckable(True)
        self.btnDeleteMode.setFlat(True)

        self.horizontalLayout.addWidget(self.btnDeleteMode)

        self.horizontalSpacer_5 = QSpacerItem(20, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_5)

        self.btnPan = QPushButton(self.menuFrame)
        self.btnPan.setObjectName(u"btnPan")
        sizePolicy5.setHeightForWidth(self.btnPan.sizePolicy().hasHeightForWidth())
        self.btnPan.setSizePolicy(sizePolicy5)
        self.btnPan.setMaximumSize(QSize(25, 25))
        self.btnPan.setBaseSize(QSize(32, 32))
        icon13 = QIcon()
        icon13.addFile(u":/icons/android-hand.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnPan.setIcon(icon13)
        self.btnPan.setIconSize(QSize(16, 16))
        self.btnPan.setCheckable(True)
        self.btnPan.setFlat(True)

        self.horizontalLayout.addWidget(self.btnPan)

        self.btnTranslate = QPushButton(self.menuFrame)
        self.btnTranslate.setObjectName(u"btnTranslate")
        sizePolicy5.setHeightForWidth(self.btnTranslate.sizePolicy().hasHeightForWidth())
        self.btnTranslate.setSizePolicy(sizePolicy5)
        self.btnTranslate.setMaximumSize(QSize(25, 25))
        self.btnTranslate.setBaseSize(QSize(32, 32))
        icon14 = QIcon()
        icon14.addFile(u":/icons/arrow-move.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnTranslate.setIcon(icon14)
        self.btnTranslate.setIconSize(QSize(16, 16))
        self.btnTranslate.setCheckable(True)
        self.btnTranslate.setChecked(True)
        self.btnTranslate.setFlat(True)

        self.horizontalLayout.addWidget(self.btnTranslate)

        self.btnScale = QPushButton(self.menuFrame)
        self.btnScale.setObjectName(u"btnScale")
        sizePolicy6.setHeightForWidth(self.btnScale.sizePolicy().hasHeightForWidth())
        self.btnScale.setSizePolicy(sizePolicy6)
        self.btnScale.setMaximumSize(QSize(25, 25))
        self.btnScale.setBaseSize(QSize(32, 32))
        icon15 = QIcon()
        icon15.addFile(u":/icons/arrow-resize.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnScale.setIcon(icon15)
        self.btnScale.setIconSize(QSize(16, 16))
        self.btnScale.setCheckable(True)
        self.btnScale.setFlat(True)

        self.horizontalLayout.addWidget(self.btnScale)

        self.btnRotate = QPushButton(self.menuFrame)
        self.btnRotate.setObjectName(u"btnRotate")
        sizePolicy5.setHeightForWidth(self.btnRotate.sizePolicy().hasHeightForWidth())
        self.btnRotate.setSizePolicy(sizePolicy5)
        self.btnRotate.setMaximumSize(QSize(25, 25))
        self.btnRotate.setBaseSize(QSize(32, 32))
        icon16 = QIcon()
        icon16.addFile(u":/icons/android-refresh.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnRotate.setIcon(icon16)
        self.btnRotate.setIconSize(QSize(16, 16))
        self.btnRotate.setCheckable(True)
        self.btnRotate.setFlat(True)

        self.horizontalLayout.addWidget(self.btnRotate)

        self.horizontalSpacer_4 = QSpacerItem(20, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_4)

        self.btnAnchor = QPushButton(self.menuFrame)
        self.btnAnchor.setObjectName(u"btnAnchor")
        sizePolicy6.setHeightForWidth(self.btnAnchor.sizePolicy().hasHeightForWidth())
        self.btnAnchor.setSizePolicy(sizePolicy6)
        self.btnAnchor.setMaximumSize(QSize(25, 25))
        self.btnAnchor.setBaseSize(QSize(32, 32))
        icon17 = QIcon()
        icon17.addFile(u":/icons/anchor.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnAnchor.setIcon(icon17)
        self.btnAnchor.setIconSize(QSize(16, 16))
        self.btnAnchor.setCheckable(True)
        self.btnAnchor.setChecked(False)
        self.btnAnchor.setFlat(True)

        self.horizontalLayout.addWidget(self.btnAnchor)

        self.comboAnchor = QComboBox(self.menuFrame)
        self.comboAnchor.addItem("")
        self.comboAnchor.addItem("")
        self.comboAnchor.addItem("")
        self.comboAnchor.addItem("")
        self.comboAnchor.addItem("")
        self.comboAnchor.addItem("")
        self.comboAnchor.addItem("")
        self.comboAnchor.setObjectName(u"comboAnchor")
        sizePolicy7 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Maximum)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.comboAnchor.sizePolicy().hasHeightForWidth())
        self.comboAnchor.setSizePolicy(sizePolicy7)
        self.comboAnchor.setMinimumSize(QSize(127, 0))
        self.comboAnchor.setMaximumSize(QSize(127, 25))
        self.comboAnchor.setLayoutDirection(Qt.LeftToRight)
        self.comboAnchor.setEditable(False)
        self.comboAnchor.setInsertPolicy(QComboBox.InsertAtCurrent)
        self.comboAnchor.setSizeAdjustPolicy(QComboBox.AdjustToContentsOnFirstShow)
        self.comboAnchor.setIconSize(QSize(0, 0))
        self.comboAnchor.setDuplicatesEnabled(False)
        self.comboAnchor.setFrame(False)
        self.comboAnchor.setModelColumn(0)

        self.horizontalLayout.addWidget(self.comboAnchor)

        self.btnToggleVisible = QPushButton(self.menuFrame)
        self.btnToggleVisible.setObjectName(u"btnToggleVisible")
        self.btnToggleVisible.setEnabled(False)
        sizePolicy6.setHeightForWidth(self.btnToggleVisible.sizePolicy().hasHeightForWidth())
        self.btnToggleVisible.setSizePolicy(sizePolicy6)
        self.btnToggleVisible.setMaximumSize(QSize(25, 25))
        self.btnToggleVisible.setBaseSize(QSize(32, 32))
        icon18 = QIcon()
        icon18.addFile(u":/icons/eye.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnToggleVisible.setIcon(icon18)
        self.btnToggleVisible.setIconSize(QSize(16, 16))
        self.btnToggleVisible.setCheckable(False)
        self.btnToggleVisible.setFlat(True)

        self.horizontalLayout.addWidget(self.btnToggleVisible)

        self.btnCustTransform = QPushButton(self.menuFrame)
        self.btnCustTransform.setObjectName(u"btnCustTransform")
        sizePolicy5.setHeightForWidth(self.btnCustTransform.sizePolicy().hasHeightForWidth())
        self.btnCustTransform.setSizePolicy(sizePolicy5)
        self.btnCustTransform.setMaximumSize(QSize(25, 25))
        self.btnCustTransform.setBaseSize(QSize(32, 32))
        icon19 = QIcon()
        icon19.addFile(u":/icons/android-expand.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnCustTransform.setIcon(icon19)
        self.btnCustTransform.setIconSize(QSize(16, 16))
        self.btnCustTransform.setFlat(True)

        self.horizontalLayout.addWidget(self.btnCustTransform)

        self.btnSendBackwards = QPushButton(self.menuFrame)
        self.btnSendBackwards.setObjectName(u"btnSendBackwards")
        self.btnSendBackwards.setEnabled(False)
        sizePolicy5.setHeightForWidth(self.btnSendBackwards.sizePolicy().hasHeightForWidth())
        self.btnSendBackwards.setSizePolicy(sizePolicy5)
        self.btnSendBackwards.setMaximumSize(QSize(25, 25))
        self.btnSendBackwards.setBaseSize(QSize(32, 32))
        icon20 = QIcon()
        icon20.addFile(u":/icons/chevron-with-circle-left.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnSendBackwards.setIcon(icon20)
        self.btnSendBackwards.setIconSize(QSize(16, 16))
        self.btnSendBackwards.setFlat(True)

        self.horizontalLayout.addWidget(self.btnSendBackwards)

        self.btnSendForwards = QPushButton(self.menuFrame)
        self.btnSendForwards.setObjectName(u"btnSendForwards")
        self.btnSendForwards.setEnabled(False)
        sizePolicy5.setHeightForWidth(self.btnSendForwards.sizePolicy().hasHeightForWidth())
        self.btnSendForwards.setSizePolicy(sizePolicy5)
        self.btnSendForwards.setMaximumSize(QSize(25, 25))
        self.btnSendForwards.setBaseSize(QSize(32, 32))
        icon21 = QIcon()
        icon21.addFile(u":/icons/chevron-with-circle-right.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnSendForwards.setIcon(icon21)
        self.btnSendForwards.setIconSize(QSize(16, 16))
        self.btnSendForwards.setFlat(True)

        self.horizontalLayout.addWidget(self.btnSendForwards)

        self.horizontalSpacer = QSpacerItem(40, 25, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.btnUndo.raise_()
        self.btnRedo.raise_()
        self.btnLoadFile.raise_()
        self.btnSave.raise_()
        self.btnViewCode.raise_()
        self.btnQuickScreenshot.raise_()
        self.btnDrawAxes.raise_()
        self.btnDrawGrid.raise_()
        self.btnSetZoom.raise_()
        self.btnPanCenter.raise_()
        self.btnResetPan.raise_()
        self.btnAlignX.raise_()
        self.btnAlignY.raise_()
        self.btnPan.raise_()
        self.btnTranslate.raise_()
        self.btnScale.raise_()
        self.btnCustTransform.raise_()
        self.btnSendBackwards.raise_()
        self.btnSendForwards.raise_()
        self.comboAnchor.raise_()
        self.btnToggleVisible.raise_()
        self.btnAnchor.raise_()
        self.btnRotate.raise_()
        self.btnSelectEdit.raise_()
        self.btnDeleteMode.raise_()

        self.verticalLayout.addWidget(self.menuFrame)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.addOption = QHBoxLayout()
        self.addOption.setSpacing(6)
        self.addOption.setObjectName(u"addOption")
        self.addOption.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.addOption.setContentsMargins(6, -1, -1, 0)
        self.btnFill = QPushButton(self.mainWidget)
        self.btnFill.setObjectName(u"btnFill")
        sizePolicy5.setHeightForWidth(self.btnFill.sizePolicy().hasHeightForWidth())
        self.btnFill.setSizePolicy(sizePolicy5)
        self.btnFill.setMaximumSize(QSize(32, 32))
        self.btnFill.setBaseSize(QSize(32, 32))
        self.btnFill.setAutoFillBackground(False)
        self.btnFill.setStyleSheet(u"")
        icon22 = QIcon()
        icon22.addFile(u":/icons/bucket.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon22.addFile(u":/icons/filledbucket.svg", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.btnFill.setIcon(icon22)
        self.btnFill.setIconSize(QSize(16, 16))
        self.btnFill.setCheckable(True)
        self.btnFill.setFlat(True)

        self.addOption.addWidget(self.btnFill)

        self.addOptionLayout = QGridLayout()
        self.addOptionLayout.setSpacing(6)
        self.addOptionLayout.setObjectName(u"addOptionLayout")

        self.addOption.addLayout(self.addOptionLayout)

        self.horizontalSpacer_7 = QSpacerItem(40, 35, QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Minimum)

        self.addOption.addItem(self.horizontalSpacer_7)

        self.label = QLabel(self.mainWidget)
        self.label.setObjectName(u"label")

        self.addOption.addWidget(self.label)

        self.txtLineWidth = QLineEdit(self.mainWidget)
        self.txtLineWidth.setObjectName(u"txtLineWidth")
        sizePolicy4.setHeightForWidth(self.txtLineWidth.sizePolicy().hasHeightForWidth())
        self.txtLineWidth.setSizePolicy(sizePolicy4)
        self.txtLineWidth.setMaximumSize(QSize(75, 16777215))

        self.addOption.addWidget(self.txtLineWidth)

        self.frameCurrColor = QFrame(self.mainWidget)
        self.frameCurrColor.setObjectName(u"frameCurrColor")
        sizePolicy4.setHeightForWidth(self.frameCurrColor.sizePolicy().hasHeightForWidth())
        self.frameCurrColor.setSizePolicy(sizePolicy4)
        self.frameCurrColor.setMinimumSize(QSize(15, 15))
        self.frameCurrColor.setAutoFillBackground(False)
        self.frameCurrColor.setStyleSheet(u"QFrame{ \n"
"padding: 4.0;\n"
"border-radius: 3.0; \n"
"background: rgb(0, 0, 0)\n"
"}")
        self.frameCurrColor.setFrameShape(QFrame.StyledPanel)
        self.frameCurrColor.setFrameShadow(QFrame.Sunken)

        self.addOption.addWidget(self.frameCurrColor)

        self.btnSelectColor = QPushButton(self.mainWidget)
        self.btnSelectColor.setObjectName(u"btnSelectColor")
        sizePolicy5.setHeightForWidth(self.btnSelectColor.sizePolicy().hasHeightForWidth())
        self.btnSelectColor.setSizePolicy(sizePolicy5)
        self.btnSelectColor.setMaximumSize(QSize(25, 25))
        self.btnSelectColor.setBaseSize(QSize(32, 32))
        self.btnSelectColor.setAutoFillBackground(False)
        self.btnSelectColor.setStyleSheet(u"")
        icon23 = QIcon()
        icon23.addFile(u":/icons/android-color-palette.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnSelectColor.setIcon(icon23)
        self.btnSelectColor.setIconSize(QSize(16, 16))
        self.btnSelectColor.setFlat(True)

        self.addOption.addWidget(self.btnSelectColor)


        self.verticalLayout_2.addLayout(self.addOption)

        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(-1, 6, -1, -1)
        self.formFrame = QFrame(self.mainWidget)
        self.formFrame.setObjectName(u"formFrame")
        sizePolicy8 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Preferred)
        sizePolicy8.setHorizontalStretch(0)
        sizePolicy8.setVerticalStretch(0)
        sizePolicy8.setHeightForWidth(self.formFrame.sizePolicy().hasHeightForWidth())
        self.formFrame.setSizePolicy(sizePolicy8)
        self.formFrame.setFrameShape(QFrame.NoFrame)
        self.formFrame.setFrameShadow(QFrame.Plain)
        self.formFrame.setLineWidth(0)
        self.formLayout = QFormLayout(self.formFrame)
        self.formLayout.setSpacing(6)
        self.formLayout.setContentsMargins(9, 9, 9, 9)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setHorizontalSpacing(0)
        self.formLayout.setVerticalSpacing(0)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.btnOpenPoly = QPushButton(self.formFrame)
        self.btnOpenPoly.setObjectName(u"btnOpenPoly")
        self.btnOpenPoly.setEnabled(True)
        sizePolicy6.setHeightForWidth(self.btnOpenPoly.sizePolicy().hasHeightForWidth())
        self.btnOpenPoly.setSizePolicy(sizePolicy6)
        self.btnOpenPoly.setMaximumSize(QSize(32, 32))
        icon24 = QIcon()
        icon24.addFile(u":/icons/openpolygon.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnOpenPoly.setIcon(icon24)
        self.btnOpenPoly.setIconSize(QSize(16, 16))
        self.btnOpenPoly.setCheckable(True)
        self.btnOpenPoly.setFlat(True)

        self.formLayout.setWidget(4, QFormLayout.ItemRole.LabelRole, self.btnOpenPoly)

        self.btnClosedPoly = QPushButton(self.formFrame)
        self.btnClosedPoly.setObjectName(u"btnClosedPoly")
        self.btnClosedPoly.setEnabled(True)
        sizePolicy6.setHeightForWidth(self.btnClosedPoly.sizePolicy().hasHeightForWidth())
        self.btnClosedPoly.setSizePolicy(sizePolicy6)
        self.btnClosedPoly.setMaximumSize(QSize(32, 32))
        icon25 = QIcon()
        icon25.addFile(u":/icons/closedpolygon.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnClosedPoly.setIcon(icon25)
        self.btnClosedPoly.setIconSize(QSize(16, 16))
        self.btnClosedPoly.setCheckable(True)
        self.btnClosedPoly.setFlat(True)

        self.formLayout.setWidget(5, QFormLayout.ItemRole.LabelRole, self.btnClosedPoly)

        self.btnOpenCurve = QPushButton(self.formFrame)
        self.btnOpenCurve.setObjectName(u"btnOpenCurve")
        self.btnOpenCurve.setEnabled(True)
        sizePolicy6.setHeightForWidth(self.btnOpenCurve.sizePolicy().hasHeightForWidth())
        self.btnOpenCurve.setSizePolicy(sizePolicy6)
        self.btnOpenCurve.setMaximumSize(QSize(32, 32))
        icon26 = QIcon()
        icon26.addFile(u":/icons/opencurve.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnOpenCurve.setIcon(icon26)
        self.btnOpenCurve.setIconSize(QSize(16, 16))
        self.btnOpenCurve.setCheckable(True)
        self.btnOpenCurve.setFlat(True)

        self.formLayout.setWidget(6, QFormLayout.ItemRole.LabelRole, self.btnOpenCurve)

        self.btnClosedCurve = QPushButton(self.formFrame)
        self.btnClosedCurve.setObjectName(u"btnClosedCurve")
        self.btnClosedCurve.setEnabled(True)
        sizePolicy6.setHeightForWidth(self.btnClosedCurve.sizePolicy().hasHeightForWidth())
        self.btnClosedCurve.setSizePolicy(sizePolicy6)
        self.btnClosedCurve.setMaximumSize(QSize(32, 32))
        icon27 = QIcon()
        icon27.addFile(u":/icons/closedcurve.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnClosedCurve.setIcon(icon27)
        self.btnClosedCurve.setIconSize(QSize(16, 16))
        self.btnClosedCurve.setCheckable(True)
        self.btnClosedCurve.setFlat(True)

        self.formLayout.setWidget(7, QFormLayout.ItemRole.LabelRole, self.btnClosedCurve)

        self.btnAddPoly = QPushButton(self.formFrame)
        self.btnAddPoly.setObjectName(u"btnAddPoly")
        self.btnAddPoly.setEnabled(True)
        sizePolicy6.setHeightForWidth(self.btnAddPoly.sizePolicy().hasHeightForWidth())
        self.btnAddPoly.setSizePolicy(sizePolicy6)
        self.btnAddPoly.setMaximumSize(QSize(32, 32))
        icon28 = QIcon()
        icon28.addFile(u":/icons/triangle-stroked-15.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnAddPoly.setIcon(icon28)
        self.btnAddPoly.setIconSize(QSize(16, 16))
        self.btnAddPoly.setCheckable(True)
        self.btnAddPoly.setFlat(True)

        self.formLayout.setWidget(8, QFormLayout.ItemRole.LabelRole, self.btnAddPoly)

        self.btnAddCircle = QPushButton(self.formFrame)
        self.btnAddCircle.setObjectName(u"btnAddCircle")
        self.btnAddCircle.setEnabled(True)
        sizePolicy6.setHeightForWidth(self.btnAddCircle.sizePolicy().hasHeightForWidth())
        self.btnAddCircle.setSizePolicy(sizePolicy6)
        self.btnAddCircle.setMaximumSize(QSize(32, 32))
        icon29 = QIcon()
        icon29.addFile(u":/icons/circle.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnAddCircle.setIcon(icon29)
        self.btnAddCircle.setIconSize(QSize(16, 16))
        self.btnAddCircle.setCheckable(True)
        self.btnAddCircle.setFlat(True)

        self.formLayout.setWidget(10, QFormLayout.ItemRole.LabelRole, self.btnAddCircle)

        self.btnAddLabel = QPushButton(self.formFrame)
        self.btnAddLabel.setObjectName(u"btnAddLabel")
        self.btnAddLabel.setEnabled(True)
        sizePolicy6.setHeightForWidth(self.btnAddLabel.sizePolicy().hasHeightForWidth())
        self.btnAddLabel.setSizePolicy(sizePolicy6)
        self.btnAddLabel.setMaximumSize(QSize(32, 32))
        icon30 = QIcon()
        icon30.addFile(u":/icons/text.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnAddLabel.setIcon(icon30)
        self.btnAddLabel.setIconSize(QSize(16, 16))
        self.btnAddLabel.setCheckable(True)
        self.btnAddLabel.setFlat(True)

        self.formLayout.setWidget(11, QFormLayout.ItemRole.LabelRole, self.btnAddLabel)

        self.btnAddFreehand = QPushButton(self.formFrame)
        self.btnAddFreehand.setObjectName(u"btnAddFreehand")
        self.btnAddFreehand.setEnabled(True)
        sizePolicy6.setHeightForWidth(self.btnAddFreehand.sizePolicy().hasHeightForWidth())
        self.btnAddFreehand.setSizePolicy(sizePolicy6)
        self.btnAddFreehand.setMaximumSize(QSize(32, 32))
        icon31 = QIcon()
        icon31.addFile(u":/icons/brush.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnAddFreehand.setIcon(icon31)
        self.btnAddFreehand.setIconSize(QSize(16, 16))
        self.btnAddFreehand.setCheckable(True)
        self.btnAddFreehand.setFlat(True)

        self.formLayout.setWidget(12, QFormLayout.ItemRole.LabelRole, self.btnAddFreehand)


        self.horizontalLayout_7.addWidget(self.formFrame)

        self.imgFrame = QFrame(self.mainWidget)
        self.imgFrame.setObjectName(u"imgFrame")
        self.imgFrame.setMinimumSize(QSize(0, 6))
        self.imgFrame.setMouseTracking(True)
        self.imgFrame.setFrameShape(QFrame.NoFrame)
        self.imgFrame.setFrameShadow(QFrame.Raised)
        self.gridLayout = QGridLayout(self.imgFrame)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(9, 9, 9, 9)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.imgLabel = QLabel(self.imgFrame)
        self.imgLabel.setObjectName(u"imgLabel")
        sizePolicy1.setHeightForWidth(self.imgLabel.sizePolicy().hasHeightForWidth())
        self.imgLabel.setSizePolicy(sizePolicy1)
        self.imgLabel.setMouseTracking(True)
        self.imgLabel.setFrameShape(QFrame.Panel)
        self.imgLabel.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)

        self.gridLayout.addWidget(self.imgLabel, 0, 1, 1, 1)


        self.horizontalLayout_7.addWidget(self.imgFrame)


        self.verticalLayout_2.addLayout(self.horizontalLayout_7)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.btnTogglePython = QPushButton(self.mainWidget)
        self.btnTogglePython.setObjectName(u"btnTogglePython")
        self.btnTogglePython.setEnabled(True)
        sizePolicy3.setHeightForWidth(self.btnTogglePython.sizePolicy().hasHeightForWidth())
        self.btnTogglePython.setSizePolicy(sizePolicy3)
        icon32 = QIcon()
        icon32.addFile(u":/icons/social-python.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnTogglePython.setIcon(icon32)
        self.btnTogglePython.setIconSize(QSize(16, 16))
        self.btnTogglePython.setCheckable(True)
        self.btnTogglePython.setFlat(True)

        self.horizontalLayout_3.addWidget(self.btnTogglePython)

        self.txtTerminalPrompt = QLineEdit(self.mainWidget)
        self.txtTerminalPrompt.setObjectName(u"txtTerminalPrompt")
        sizePolicy2.setHeightForWidth(self.txtTerminalPrompt.sizePolicy().hasHeightForWidth())
        self.txtTerminalPrompt.setSizePolicy(sizePolicy2)

        self.horizontalLayout_3.addWidget(self.txtTerminalPrompt)

        self.btnEnterCommand = QPushButton(self.mainWidget)
        self.btnEnterCommand.setObjectName(u"btnEnterCommand")
        self.btnEnterCommand.setEnabled(True)
        sizePolicy3.setHeightForWidth(self.btnEnterCommand.sizePolicy().hasHeightForWidth())
        self.btnEnterCommand.setSizePolicy(sizePolicy3)
        icon33 = QIcon()
        icon33.addFile(u":/icons/subdirectory-left.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnEnterCommand.setIcon(icon33)
        self.btnEnterCommand.setIconSize(QSize(16, 16))
        self.btnEnterCommand.setFlat(True)

        self.horizontalLayout_3.addWidget(self.btnEnterCommand)


        self.verticalLayout_2.addLayout(self.horizontalLayout_3)


        self.horizontalLayout_2.addLayout(self.verticalLayout_2)


        self.verticalLayout.addLayout(self.horizontalLayout_2)


        self.horizontalLayout_4.addWidget(self.mainWidget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1000, 26))
        self.menuFIle = QMenu(self.menubar)
        self.menuFIle.setObjectName(u"menuFIle")
        self.menuOpenRecent = QMenu(self.menuFIle)
        self.menuOpenRecent.setObjectName(u"menuOpenRecent")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuOptions = QMenu(self.menubar)
        self.menuOptions.setObjectName(u"menuOptions")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setSizeGripEnabled(False)
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFIle.addAction(self.actionNewFile)
        self.menuFIle.addAction(self.actionOpen)
        self.menuFIle.addAction(self.menuOpenRecent.menuAction())
        self.menuFIle.addAction(self.actionSave)
        self.menuFIle.addAction(self.actionSaveAs)
        self.menuFIle.addAction(self.actionExportToAsy)
        self.menuFIle.addAction(self.actionExportAsymptote)
        self.menuFIle.addSeparator()
        self.menuFIle.addAction(self.actionQuit)
        self.menuOpenRecent.addSeparator()
        self.menuOpenRecent.addAction(self.actionClearRecent)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuOptions.addAction(self.actionSettings)
        self.menuOptions.addAction(self.actionKeymaps)
        self.menuHelp.addAction(self.actionManual)
        self.menuHelp.addAction(self.actionAbout)
        self.menuTools.addAction(self.actionEnterCommand)

        self.retranslateUi(MainWindow)

        self.comboAnchor.setCurrentIndex(0)
        self.btnFill.setDefault(False)
        self.btnSelectColor.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"xasy", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"&About", None))
        self.actionManual.setText(QCoreApplication.translate("MainWindow", u"&Manual", None))
        self.actionSettings.setText(QCoreApplication.translate("MainWindow", u"&Settings", None))
        self.actionPause.setText(QCoreApplication.translate("MainWindow", u"Pause ", None))
        self.actionSaveAs.setText(QCoreApplication.translate("MainWindow", u"&Save as", None))
        self.actionEnterCommand.setText(QCoreApplication.translate("MainWindow", u"&Enter Command", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"&Quit", None))
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"&Undo", None))
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"&Redo", None))
        self.actionShow_Grid.setText(QCoreApplication.translate("MainWindow", u"&Show Grid", None))
        self.actionShow_Local_Grid.setText(QCoreApplication.translate("MainWindow", u"Show &Local Grid", None))
        self.actionTransform.setText(QCoreApplication.translate("MainWindow", u"&Transform", None))
        self.actionExportAsymptote.setText(QCoreApplication.translate("MainWindow", u"Export as...", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionClearRecent.setText(QCoreApplication.translate("MainWindow", u"Clear Menu", None))
        self.actionNewFile.setText(QCoreApplication.translate("MainWindow", u"New File", None))
        self.actionExportToAsy.setText(QCoreApplication.translate("MainWindow", u"Export as Asy", None))
        self.actionKeymaps.setText(QCoreApplication.translate("MainWindow", u"&Keymaps", None))
#if QT_CONFIG(tooltip)
        self.btnUndo.setToolTip(QCoreApplication.translate("MainWindow", u"Undo", None))
#endif // QT_CONFIG(tooltip)
        self.btnUndo.setText("")
#if QT_CONFIG(tooltip)
        self.btnRedo.setToolTip(QCoreApplication.translate("MainWindow", u"Redo", None))
#endif // QT_CONFIG(tooltip)
        self.btnRedo.setText("")
#if QT_CONFIG(tooltip)
        self.btnLoadFile.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Open file</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnLoadFile.setText("")
#if QT_CONFIG(tooltip)
        self.btnSave.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Save file</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnSave.setText("")
#if QT_CONFIG(tooltip)
        self.btnViewCode.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Edit code</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnViewCode.setText("")
#if QT_CONFIG(tooltip)
        self.btnQuickScreenshot.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Screenshot</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnQuickScreenshot.setText("")
#if QT_CONFIG(tooltip)
        self.btnDrawAxes.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Toggle display axes</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnDrawAxes.setText("")
#if QT_CONFIG(tooltip)
        self.btnDrawGrid.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Toggle grid</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnDrawGrid.setText("")
#if QT_CONFIG(tooltip)
        self.btnSetZoom.setToolTip(QCoreApplication.translate("MainWindow", u"Zoom", None))
#endif // QT_CONFIG(tooltip)
        self.btnSetZoom.setText("")
#if QT_CONFIG(tooltip)
        self.btnPanCenter.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Center</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnPanCenter.setText("")
#if QT_CONFIG(tooltip)
        self.btnResetPan.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Center about origin</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnResetPan.setText("")
#if QT_CONFIG(tooltip)
        self.btnAlignX.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Lock transform to X axis</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnAlignX.setText(QCoreApplication.translate("MainWindow", u"X", None))
#if QT_CONFIG(tooltip)
        self.btnAlignY.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Lock transform to Y axis</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnAlignY.setText(QCoreApplication.translate("MainWindow", u"Y", None))
#if QT_CONFIG(tooltip)
        self.btnSelectEdit.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>B\u00e9zier editor</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnSelectEdit.setText("")
#if QT_CONFIG(tooltip)
        self.btnDeleteMode.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Delete</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnDeleteMode.setText("")
#if QT_CONFIG(tooltip)
        self.btnPan.setToolTip(QCoreApplication.translate("MainWindow", u"Pan", None))
#endif // QT_CONFIG(tooltip)
        self.btnPan.setText("")
#if QT_CONFIG(tooltip)
        self.btnTranslate.setToolTip(QCoreApplication.translate("MainWindow", u"Translate", None))
#endif // QT_CONFIG(tooltip)
        self.btnTranslate.setText("")
#if QT_CONFIG(tooltip)
        self.btnScale.setToolTip(QCoreApplication.translate("MainWindow", u"Scale", None))
#endif // QT_CONFIG(tooltip)
        self.btnScale.setText("")
#if QT_CONFIG(tooltip)
        self.btnRotate.setToolTip(QCoreApplication.translate("MainWindow", u"Rotate", None))
#endif // QT_CONFIG(tooltip)
        self.btnRotate.setText("")
#if QT_CONFIG(tooltip)
        self.btnAnchor.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Set custom anchor</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnAnchor.setText("")
        self.comboAnchor.setItemText(0, QCoreApplication.translate("MainWindow", u"Center", None))
        self.comboAnchor.setItemText(1, QCoreApplication.translate("MainWindow", u"Origin", None))
        self.comboAnchor.setItemText(2, QCoreApplication.translate("MainWindow", u"Top Left", None))
        self.comboAnchor.setItemText(3, QCoreApplication.translate("MainWindow", u"Top Right", None))
        self.comboAnchor.setItemText(4, QCoreApplication.translate("MainWindow", u"Bottom Right", None))
        self.comboAnchor.setItemText(5, QCoreApplication.translate("MainWindow", u"Bottom Left", None))
        self.comboAnchor.setItemText(6, QCoreApplication.translate("MainWindow", u"Custom", None))

#if QT_CONFIG(tooltip)
        self.comboAnchor.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Anchor</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.comboAnchor.setCurrentText(QCoreApplication.translate("MainWindow", u"Center", None))
        self.btnToggleVisible.setText("")
#if QT_CONFIG(tooltip)
        self.btnCustTransform.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnCustTransform.setText("")
#if QT_CONFIG(tooltip)
        self.btnSendBackwards.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnSendBackwards.setText("")
#if QT_CONFIG(tooltip)
        self.btnSendForwards.setToolTip(QCoreApplication.translate("MainWindow", u"Translate", None))
#endif // QT_CONFIG(tooltip)
        self.btnSendForwards.setText("")
#if QT_CONFIG(tooltip)
        self.btnFill.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Toggle fill/outline</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnFill.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"Line Width:", None))
#if QT_CONFIG(tooltip)
        self.txtLineWidth.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Current pen width</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.frameCurrColor.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Current pen color</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.btnSelectColor.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Set color</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnSelectColor.setText("")
#if QT_CONFIG(tooltip)
        self.btnOpenPoly.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Open polygon</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnOpenPoly.setText("")
#if QT_CONFIG(tooltip)
        self.btnClosedPoly.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Closed polygon</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnClosedPoly.setText("")
#if QT_CONFIG(tooltip)
        self.btnOpenCurve.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Open B\u00e9zier curve</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnOpenCurve.setText("")
#if QT_CONFIG(tooltip)
        self.btnClosedCurve.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Closed B\u00e9zier curve</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnClosedCurve.setText("")
#if QT_CONFIG(tooltip)
        self.btnAddPoly.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Regular polygon</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnAddPoly.setText("")
#if QT_CONFIG(tooltip)
        self.btnAddCircle.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Circle</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnAddCircle.setText("")
#if QT_CONFIG(tooltip)
        self.btnAddLabel.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Text</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnAddLabel.setText("")
#if QT_CONFIG(tooltip)
        self.btnAddFreehand.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Freehand</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnAddFreehand.setText("")
        self.imgLabel.setText("")
        self.btnTogglePython.setText("")
        self.btnEnterCommand.setText("")
        self.menuFIle.setTitle(QCoreApplication.translate("MainWindow", u"&File", None))
        self.menuOpenRecent.setTitle(QCoreApplication.translate("MainWindow", u"Open Recent", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"&Edit", None))
        self.menuOptions.setTitle(QCoreApplication.translate("MainWindow", u"Optio&ns", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"&Help", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"&Tools", None))
    # retranslateUi

