.TH DVIHP 1 "December 24, 2009"
.\" man page by Jim Van Zandt <jrv@vanzandt.mv.com>         -*- nroff -*-
.SH NAME
dvihp \- convert a TeX DVI file to Hewlett-Packard PCL
.SH SYNOPSIS
\fBdvihp\fP [\fIoptions\fP] \fIdvifile\fP[.dvi]
.SH DESCRIPTION
\fBdvihp\fP translates the given \fIdvifile\fP to Hewlett-Packard PCL
using \fBdvicopy\fP(1) then $DVILJ (dvilj4 by default).
.P
In the absence of other options, pipe the PCL to $SPOOL (lpr by default).
.SH OPTIONS
Options are recognized from dvips where possible:
.IP \fB-A\fP
print odd pages
.IP \fB-B\fP
print even pages
.IP "\fB-d\fP \fIn\fP"
set debug bits to \fIn\fP (see documentation)
.IP "\fB-D\fP \fIn\fP"
set resolution to \fIn\fP
.IP \fB-f\fP
run as filter
.IP "\fB-l\fP \fIn\fP"
don't print pages after \fIn\fP
.IP \fB-m\fP
manual feed
.IP "\fB-n\fP \fIn\fP"
print \fIn\fP pages
.IP "\fB-O\fP \fIa\fP,\fIb\fP"
set/change paper offset to \fIa\fP,\fIb\fP mm.
.IP "\fB-o\fP \fIs\fP"
output to \fIs\fP instead of spooling
.IP "\fB-p\fP \fIn\fP"
don't print pages before \fIn\fP.
.IP \fB-Ps\fP
pass directly to lpr.
.IP \fB-v\fP
verbose operation.
.IP "\fB-x\fP \fIn\fP"  
set magnification to \fIn\fP.
.IP \fB--help\fP
write usage summary.
.P
Other options are passed to the dvilj program.
.SH BUGS
Email bug reports to tex-k@tug.org.
.SH SEE ALSO
\fBdvicopy\fP(1), \fBdvilj4\fP(1).
