.\" e
.TH MAG 1 "1 Feb 2016"
.de EX
.sp
.in +5
.nf
.ft CW
..
.de EE
.in -5
.ft R
.sp
.fi
..
.SH NAME
mag \- computes TeX fontsizes and magsteps
.SH SYNOPSIS 
.B
mag
[-\fBR\fIdpi\fP\fP] magstep . . .

.B
mag
[-\fBr\fP] [-\fBR\fP\fIdpi\fP] fontsize . . .

.SH DESCRIPTION
.EQ
delim $$
.EN
This tool calculates fontsizes given magsteps.  TeXfonts are provided as
true sized fonts or as magnifications.  The fontsize of a true sized
font equals the resolution of the printer (ex.  300).  The fontsize
of a font magnified $n$ \fImagsteps\fP equals:
.EQ
1.2 sup{n} times 300
delim off
.EN
rounded to its nearest integer value.  Fontnames for TeX fonts normally
consists of the name (\fIcmr\fP), pointsize (\fI10\fP), type (\fIpk\fP)
and fontsize (\fI360\fP), for example: \fIcmr10.360pk\fP. 

.SH EXAMPLES
The result of \fImag -R240 -2 0 0.5 1\fP will be: 
.EX 
167 240 263 288 
.EE

The inverse function is computed with the \fI-r\fP option. The result of
\fImag -r -R240 167 240 263 288\fP
will be the fontsteps:
.EX
-2 0 0.5 1
.EE

The UNIX shells allow command substitution. One can write:
.EX
mag -r -R240 `mag -R240 -2 0 0.5 1`
.EE

.SH DATE
18 December, 1989

.SH AUTHOR
.nf
Piet Tutelaers
University of Technology Eindhoven
Maintained in TeX Live; please send bug reports or other correspondence
to tex-k@tug.org (http://lists.tug.org/tex-k).
