.TH prepmx 1 "08 January 2018" "M-Tx Version 0.63" "prepmx Manual Page"
.SH NAME
prepmx \- preprocessor for PMX, easy music typesetting program
.SH SYNOPSIS
.B prepmx
.RI [ options ]
.I jobname
.RI [ outdir/ ]
.RI [ stylefile ]
.SH DESCRIPTION
.B M-Tx
is an easy to use preprocessor language for the
.B PMX
music typesetting program, aimed at people who are not experts.  For an
easy example, have a look at the following example:

  c2+       e4    g   | b4d-  c1 d c2        |
  c8 g+ e g c- g+ e g | d g f g    c- g+ e g |

For syntax reference, please look at the M-Tx manual written by Dirk
Laurie, the creator of the M-Tx language and the author of 
.BR prepmx (1), 
its command-line utility.

.B prepmx
processes the file
.IR jobname .mtx
to generate
.IR jobname .pmx.
You can then process this file using the 
.BR pmxab (1)
command, which is a preprocessor for MusiXTeX.

.I outdir/
is the directory where `pmx' will put the final .tex file. Note that the
trailing slash is mandatory. You can provide a
.I stylefile
for M-Tx. If omitted, the file `mtxstyle.txt' in the current
directory is used, if there is one.
.SH OPTIONS
Options can also be specified in a `Options:' line in the preamble,
which takes precedence over the command line.
.TP
.B \-b
disable unbeamVocal
.TP
.B \-c
disable doChords
.TP
.B \-D
enable debugMode
.TP
.B \-f
enable solfaNoteNames
.TP
.B \-i
enable ignoreErrors
.TP
.B \-m
disable doLyrics
.TP
.B \-n
enable instrumentNames
.TP
.B \-t
disable doUptext
.TP
.B \-u
disable uptextOnRests
.TP
.B \-v
enable beVerbose
.TP
.B \-w
enable pedanticWarnings
.TP
.BI \- n
select Special Case 
.I n
.TP
.B \-H
print enabled status of all options
.SH EXIT STATUS
If no error was found,
.B prepmx
exits with return code 0.  In case of an error, the line number of the
processed line is returned. This may not always be the line containing
the actual error. A return status of 10000 means that the input file was
empty or could not be opened.
.SH SEE ALSO
.B M-Tx
User's Guide (mtxdoc.pdf)
.br
pmxab(1), musixtex(1)
.SH AUTHORS
prepmx was written by Dirk Laurie <dirk.laurie@gmail.com>. This
manual page was written by Roland Stigge <stigge@antcom.de>
for the Debian project. It was revised and extended by
Nis Martensen <nis.martensen@web.de> and Bob Tennent
<rdt@cs.queensu.ca>.
