@q This file tells CWEAVE to treat X11/Xlib types as reserved words. @>

@s XExtData int
@s XExtCodes int
@s _XExtension int
@s XPixmapFormatValues int
@s XGCValues int
@s GC int
@s Visual int
@s Depth int
@s Screen int
@s ScreenFormat int
@s XSetWindowAttributes int
@s XWindowAttributes int
@s XHostAddress int
@s XImage int
@s XWindowChanges int
@s XColor int
@s XSegment int
@s XPoint int
@s XRectangle int
@s XArc int
@s XKeyboardControl int
@s XKeyboardState int
@s XTimeCoord int
@s XModifierKeymap int
@s Display int
@s XKeyEvent int
@s XKeyPressedEvent int
@s XKeyReleasedEvent int
@s XButtonEvent int
@s XButtonPressedEvent int
@s XButtonReleasedEvent int
@s XMotionEvent int
@s XPointerMovedEvent int
@s XCrossingEvent int
@s XEnterWindowEvent int
@s XLeaveWindowEvent int
@s XFocusChangeEvent int
@s XFocusInEvent int
@s XFocusOutEvent int
@s XKeymapEvent int
@s XExposeEvent int
@s XGraphicsExposeEvent int
@s XNoExposeEvent int
@s XVisibilityEvent int
@s XCreateWindowEvent int
@s XDestroyWindowEvent int
@s XUnmapEvent int
@s XMapEvent int
@s XMapRequestEvent int
@s XReparentEvent int
@s XConfigureEvent int
@s XGravityEvent int
@s XResizeRequestEvent int
@s XConfigureRequestEvent int
@s XCirculateEvent int
@s XCirculateRequestEvent int
@s XPropertyEvent int
@s XSelectionClearEvent int
@s XSelectionRequestEvent int
@s XSelectionEvent int
@s XColormapEvent int
@s XClientMessageEvent int
@s XMappingEvent int
@s XErrorEvent int
@s XAnyEvent int
@s XEvent int
@s _XQEvent int
@s XCharStruct int
@s XFontProp int
@s XFontStruct int
@s XTextItem int
@s XChar2b int
@s XTextItem16 int
@s XEDataObject int
@s XErrorHandler int
@s XIOErrorHandler int
@s XID int
@s Window int
@s Drawable int
@s Font int
@s Pixmap int
@s Cursor int
@s Colormap int
@s GContext int
@s KeySym int
@s Mask int
@s Atom int
@s VisualID int
@s Time int
@s KeyCode int
