@q This file tells CWEAVE to treat XView types as reserved words. @>

@s Attr_attribute int
@s Attr_avlist int
@s Attr_base_cardinality int
@s Attr_base_type int
@s Attr_cu_type int
@s Attr_generic int
@s Attr_list_ptr_type int
@s Attr_list_type int
@s Attr_pkg int
@s Attr_union int
@s Canvas int
@s Canvas_attribute int
@s Canvas_paint_attribute int
@s Canvas_paint_window int
@s Canvas_view int
@s Canvas_view_attribute int
@s Cms int
@s Cms_attribute int
@s Cms_type int
@s Cursor_attribute int
@s Cursor_drag_state int
@s Cursor_drag_type int
@s Defaults_pairs int
@s Destroy_status int
@s Dnd int
@s DndDragType int
@s Dnd_attribute int
@s Drag_drop int
@s Drawable_attr int
@s Drawable_attribute int
@s Drop_site_item int
@s Enumerator int
@s Error_attr int
@s Error_attribute int
@s Error_layer int
@s Error_severity int
@s Event int
@s Firm_event int
@s Font_attribute int
@s Font_string_dims int
@s Font_type int
@s Frame int
@s Frame_accelerator int
@s Frame_attribute int
@s Frame_cmd int
@s Frame_cmd_pin_state int
@s Frame_focus_direction int
@s Frame_help int
@s Frame_props int
@s Fullscreen int
@s Fullscreen_attr int
@s Fullscreen_attribute int
@s Fullscreen_grab_mode int
@s Icon int
@s Icon_attribute int
@s Inputmask int
@s Kbd_cmds_value int
@s Menu int
@s Menu_attribute int
@s Menu_class int
@s Menu_feedback int
@s Menu_generate int
@s Menu_item int
@s Notice_attribute int
@s Notify_arg int
@s Notify_client int
@s Notify_copy int
@s Notify_dump_type int
@s Notify_error int
@s Notify_event int
@s Notify_event_type int
@s Notify_func int
@s Notify_release int
@s Notify_signal_mode int
@s Notify_value int
@s Openwin int
@s Openwin_attribute int
@s Openwin_split_direction int
@s Panel int
@s Panel_abbrev_menu_button_item int
@s Panel_attr int
@s Panel_attribute int
@s Panel_attribute_value int
@s Panel_button_item int
@s Panel_choice_item int
@s Panel_drop_target_item int
@s Panel_gauge_item int
@s Panel_item int
@s Panel_item_type int
@s Panel_list_item int
@s Panel_list_mode int
@s Panel_list_op int
@s Panel_message_item  int
@s Panel_multiline_text_item int
@s Panel_numeric_text_item int
@s Panel_ops int
@s Panel_paint_window int
@s Panel_setting int
@s Panel_slider_item int
@s Panel_status int
@s Panel_text_item int
@s Panel_view int
@s Pixwin int
@s Pw_pixel_cache int
@s Rect int
@s Rectlist int
@s Rectnode int
@s Screen_attr int
@s Screen_attribute int
@s Scroll_motion int
@s Scrollable_panel int
@s Scrollbar int
@s Scrollbar_attr int
@s Scrollbar_attribute int
@s Scrollbar_motion int
@s Scrollbar_setting int
@s Sel_cmpat_info int
@s Sel_prop_info int
@s Selection int
@s Selection_attr int
@s Selection_attribute int
@s Selection_item int
@s Selection_owner int
@s Selection_requestor int
@s Seln_access int
@s Seln_attribute int
@s Seln_client int
@s Seln_file_info int
@s Seln_function int
@s Seln_function_buffer int
@s Seln_functions_state int
@s Seln_holder int
@s Seln_holders_all int
@s Seln_inform_args int
@s Seln_level int
@s Seln_rank int
@s Seln_replier_data int
@s Seln_request int
@s Seln_requester int
@s Seln_response int
@s Seln_result int
@s Seln_state int
@s Server_attr int
@s Server_attribute int
@s Server_image int
@s Server_image_attribute int
@s Termsw int
@s Termsw_attribute int
@s Termsw_mode int
@s Termsw_view int
@s Text int
@s Textsw int
@s Textsw_action int
@s Textsw_attribute int
@s Textsw_enum int
@s Textsw_expand_status int
@s Textsw_filter_attribute int
@s Textsw_filter_command int
@s Textsw_index int
@s Textsw_mark int
@s Textsw_menu_cmd int
@s Textsw_opaque int
@s Textsw_status int
@s Textsw_view int
@s Tty int
@s Tty_attribute int
@s Tty_view int
@s Ttysubwindow int
@s Vuid_addr_probe int
@s Vuid_device int
@s WM_Direction int
@s Win_enum_node int
@s Win_enum_result int
@s Win_tree_layer int
@s Window_attr int
@s Window_attribute int
@s Window_handle int
@s Window_input_event int
@s Window_layout_op int
@s Window_rescale_rect_obj int
@s Window_rescale_state int
@s Window_type int
@s Ws_scale int
@s Ws_scale_list int
@s Xv_Color_info int
@s Xv_Cursor int
@s Xv_Drawable int
@s Xv_Font int
@s Xv_Notice int
@s Xv_Screen int
@s Xv_Server int
@s Xv_Window int
@s Xv_attr int
@s Xv_attribute int
@s Xv_base int
@s Xv_canvas int
@s Xv_canvas_pw int
@s Xv_canvas_view int
@s Xv_cms_struct int
@s Xv_cmsdata int
@s Xv_cursor int
@s Xv_cursor_struct int
@s Xv_dnd_struct int
@s Xv_drag_drop int
@s Xv_drawable int
@s Xv_drawable_struct int
@s Xv_drop_site int
@s Xv_drop_site_struct int
@s Xv_embedding int
@s Xv_focus_rank int
@s Xv_font int
@s Xv_font_struct int
@s Xv_frame_base int
@s Xv_frame_class int
@s Xv_frame_cmd int
@s Xv_frame_help int
@s Xv_frame_props int
@s Xv_fullscreen int
@s Xv_generic_attr int
@s Xv_generic_attribute int
@s Xv_generic_struct int
@s Xv_icon int
@s Xv_icon_header_info int
@s Xv_item int
@s Xv_menu int
@s Xv_menu_item int
@s Xv_Notice int
@s Xv_notice int
@s Xv_notice_struct int
@s Xv_object int
@s Xv_opaque int
@s Xv_openwin int
@s Xv_panel int
@s Xv_panel_ambtn int
@s Xv_panel_button int
@s Xv_panel_choice int
@s Xv_panel_drop int
@s Xv_panel_extension_item int
@s Xv_panel_gauge int
@s Xv_panel_list int
@s Xv_panel_message int
@s Xv_panel_multiline_text int
@s Xv_panel_num_text int
@s Xv_panel_or_item int
@s Xv_panel_slider int
@s Xv_panel_text int
@s Xv_panel_view int
@s Xv_pkg int
@s Xv_Screen int
@s Xv_screen int
@s Xv_screen_struct int
@s Xv_scrollbar int
@s Xv_sel int
@s Xv_sel_item int
@s Xv_sel_owner int
@s Xv_sel_requestor int
@s Xv_Server int
@s Xv_server int
@s Xv_server_image int
@s Xv_server_struct int
@s Xv_singlecolor int
@s Xv_termsw int
@s Xv_termsw_view int
@s Xv_textsw int
@s Xv_textsw_view int
@s Xv_tty int
@s Xv_tty_view int
@s Xv_window int
@s Xv_window_struct int
@s Xv_xrectlist int
@s icon_header_handle int
@s icon_header_object int
