name: Build Binary

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: sudo apt install automake autoconf libtool texinfo texi2html gcc ruby make
      - name: build
        run: ./build-gcc/build-aptex.sh
      - name: test
        run: cd test && sh run.sh
      - name: pack
        run: tar cvf aptex-linux-x64.tar.gz src/aptex
      - name: release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: aptex-linux-x64.tar.gz
          asset_name: app-linux-x64.tar.gz
          tag: ${{ github.ref }}-${{ github.run_id }}
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: ./build-gcc/build-aptex.sh
      - name: test
        run: cd test && sh run.sh
      - name: pack
        run: tar cvf aptex-macOS.tar.gz src/aptex
      - name: release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: aptex-macOS.tar.gz
          asset_name: app-macOS.tar.gz
          tag: ${{ github.ref }}-${{ github.run_id }}
